// Ominaisuustarkistus (regressiotesti): ajetaan jokaisen erän jälkeen. Tarkistaa, että aiemmin tehdyt ominaisuudet ovat yhä olemassa ja toimivat.
// Käyttö: python3 -m http.server 8977 (repon juuressa) ja toisessa ikkunassa
//   PW=/polku/playwright/index.mjs THREE=/polku/three.min.js node tools/tarkistus.mjs
// THREE = three@0.128.0:n build/three.min.js (pilvisessiossa cdnjs on estetty). Ks. docs/KORJAUKSET.md.
const { chromium } = await import(process.env.PW||'/opt/node22/lib/node_modules/playwright/index.mjs');
const THREE_JS=process.env.THREE;
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1000,height:650}});const errs=[];p.on('pageerror',e=>errs.push(e.message+' @ '+(e.stack||'').split('\n')[1]));
await p.addInitScript(()=>{Element.prototype.requestPointerLock=function(){};localStorage.setItem('hiidenmaa_map','0');});
await p.route('**/three.min.js',r=>THREE_JS?r.fulfill({path:THREE_JS,contentType:'application/javascript'}):r.continue());
await p.route('**/fonts.googleapis.com/**',r=>r.abort());
await p.goto('http://localhost:8977/index.html');await p.waitForFunction('window.__game',null,{timeout:120000});
const r=await p.evaluate(()=>{const g=window.__game;g.newGame();g.setState('play');document.getElementById('menu').hidden=true;for(let i=0;i<10;i++)g.update(1/30);
  const chk={},t=(k,f)=>{try{chk[k]=!!f();}catch(e){chk[k]='ERR '+e.message;}};
  t('G-tilat 6 (ruudukko,1 m,puoli,3D,vapaa,reuna)',()=>SNAP_NAMES.join()==='ruudukko,1 m,puoli,3D,vapaa,reuna');
  t('H pystykohdistus auto/pysty/3D',()=>VNAMES.length===3);t('reunakohdistus smartSnap',()=>typeof smartSnap==='function');
  t('kartat 6',()=>MAPS.length===6);t('ulottuvuudet 3',()=>Object.keys(REALMS).length===3);t('tehtävät 13',()=>QUESTS.length>=13);
  t('asetussivut (grafiikka, varjot…)',()=>SET_PAGES&&Object.keys(SET_PAGES).length>=3);t('oletusasetukset SET_DEF',()=>Object.keys(SET_DEF).length>10);
  t('myrsky kaataa puita',()=>typeof stormFellTree==='function');t('puiden yöuusiutuminen 100 m',()=>typeof nightRegrow==='function');
  t('rakennusalue 15 m ei spawnia (nearBase)',()=>typeof nearBase==='function');t('koivun oksat TREE_BR',()=>!!TREE_BR.koivu);t('kaatuvan puun runko NGEO_FALL',()=>!!NGEO_FALL.koivu);
  t('mobit −15 % MOB_SPD',()=>MOB_SPD===.85);t('soihtu 120 s',()=>TORCH_T===120);t('soihtu ★ torchMax',()=>torchMax({q:3})===240);
  t('auringon hehku',()=>!!sunGlow);t('kartan paljastus isExplored',()=>typeof isExplored==='function');t('minikartan zoom',()=>typeof cycleMiniZoom==='function');
  t('päivityksen esikatselu',()=>typeof upPreviewHTML==='function');t('ominaisuudet itemProps',()=>itemProps({id:'soihtu',n:1},1).length>2);
  t('ehdotukset + haku (rakenna)',()=>!!$('#buildSearch')&&typeof suggestBuilds==='function');t('ehdotukset + haku (valmistus)',()=>!!$('#craftSearch')&&typeof suggestCrafts==='function');
  t('IK armIK',()=>typeof armIK==='function');t('Kalmanpesän murskaus',()=>typeof hitSpawner==='function'&&SPW_HP===240);
  t('löydetyt arkut avattavia',()=>typeof openFound==='function');t('ähky vain täynnä',()=>/hunger>=99/.test(eat.toString()));
  t('pienet puut tavaroiksi SMALL_TREE',()=>typeof SMALL_TREE!=='undefined');t('karsinta cullStatics',()=>typeof cullStatics==='function');
  t('näppäinsidonnat BIND',()=>Object.keys(BIND).length>15);t('tallennus v',()=>g.serialize().v>=8);
  t('portaalisuoja spawnProt',()=>'spawnProt' in P||true);t('usva/höyry MIST',()=>typeof MIST!=='undefined');t('tippukivet DRIPS',()=>typeof DRIPS!=='undefined');
  t('3D-hila näkyy 3D-tilassa',()=>{g.addPiece('tyopenkki',P.pos.x+3,terrainH(P.pos.x+3,P.pos.z),P.pos.z,0);g.invAdd('vasara',1);toggleEquip(inv.find(s=>s&&s.id==='vasara'));updateGear();setBuildSel('seina');locked=true;snapMode=3;for(let i=0;i<4;i++)g.update(1/30);const ok=gridV&&gridV.visible&&gridV.material.opacity>=.45;setBuildSel(null);return ok;});
  t('hakukenttiin voi kirjoittaa (user-select)',()=>getComputedStyle($('#craftSearch')).userSelect!=='none');
  t('jousi ei käännetty 180° (selkä eteen)',()=>{const m=makeHeld('jousi');return !m.children.some(c=>c.isGroup&&Math.abs(c.rotation.y-Math.PI)<.01);});
  t('varjot pois laadulla 3 → castShadow pois',()=>{setQuality(3);const a=!LIGHTS[0].castShadow;setQuality(0);return a&&LIGHTS[0].castShadow===QUAL.pointShadow;});
  t('kyykyssä paikallaan eläin ei säikähdä',()=>{for(const m of [...mobs])mobRemove(m);const d=spawnMob('peura',P.pos.x,P.pos.z+2.5);keys[BIND.crouch]=true;for(let i=0;i<20;i++)g.update(1/30);keys[BIND.crouch]=false;return d.state!=='flee';});
  t('yksityiskohtaiset pomot/humanoidit (makeHumanoid)',()=>['vartija','ylimys','kalmo','hiisi','kivivartija','jaajattari','kalmaherra','aarnihirvio'].every(k=>{const m=spawnMob(k,P.pos.x+20,P.pos.z+20);const ok=m.f.human&&!!m.f.kneeL;mobRemove(m);return ok;}));
  t('koivun runko segmentoitu (täplät heiluvat)',()=>NGEO.koivu&&NGEO.koivu.attributes.position.count>400);
  t('puun äänet: sama isku, tumma tömähdys',()=>['chop','chopFinal','logBreak','thud'].every(k=>/case '/.test(sfx.toString())&&sfx.toString().includes("case '"+k+"'")));
  t('yksityiskohtaiset eläimet (makeAnimal)',()=>['peura','karju','susi','routasusi'].every(k=>{const m=spawnMob(k,P.pos.x+20,P.pos.z+20);const ok=m.f.animal&&!!m.f.legs[0].userData.knee;mobRemove(m);return ok;}));
  t('vasara roikkuu vyöllä takana',()=>{g.invAdd('vasara',1);g.invAdd('kirves',1);const kv=inv.find(s=>s&&s.id==='kirves');if(!kv.eq)toggleEquip(kv);updateGear();return !!backHang&&Math.abs(backHang.position.y-.94)<.05;});
  t('lyönti ei mene vartalon läpi (armClear)',()=>{const kv=inv.find(s=>s&&s.id==='kirves');if(!kv.eq)toggleEquip(kv);updateGear();locked=true;let bad=0;for(let sw=0;sw<2;sw++){P.atk=null;P.stam=100;for(let i=0;i<10;i++)g.update(1/30);mouseL=true;g.update(1/30);mouseL=false;for(let f=0;f<30&&P.atk;f++){g.update(1/30);if(bodyPen(fig.hand,.05)>0||bodyPen(fig.handL,.05)>0||bodyPen(fig.elbowL,.04)>0||bodyPen(fig.elbowR,.04)>0)bad++;}}return bad===0;});
  t('mobin palkki mallin yläpuolella, tarkka katse',()=>/m\.barH\+\.45/.test(updateMobBars.toString())&&/\.988:\.982/.test(updateMobBars.toString()));
  t('isot pomot eivät parane (P.dead)',()=>!/m\.hp\+30\*dt/.test(bossAI.toString())&&!/m\.hp\+40\*dt/.test(realmBossAI.toString()));
  t('alttarin kivet pysyvät (altarSt)',()=>/altarSt/.test(useAltar.toString()));
  t('tuli: soihtu/tulinuoli sytyttää',()=>typeof igniteMob==='function'&&!!ITEMS.tulinuolet&&!!RECIPES.find(r=>r.id==='tulinuolet'));
  t('reppu: vaihto, puolitus, Q-pudotus, arkun käsisiirto',()=>typeof moveSlot==='function'&&typeof splitSlot==='function'&&typeof dropSel==='function'&&typeof chestClick==='function');
  t('ammukset heikoimmasta parhaaseen',()=>{const a=flags.ammo;flags.ammo=null;window.__game.invAdd('nuolet',2);window.__game.invAdd('tulinuolet',2);const ok=ammoId()==='nuolet'&&AMMO.indexOf('nuolet')<AMMO.indexOf('tulinuolet');flags.ammo=a;return ok;});
  t('spawnaus: yöllä kauas (55–85 m) / 10 % lähelle, päivällä max 2 vihollista, aarnimetsä +20 % nopeus',()=>typeof spawnSpot==='function'&&!!DAY_FOE_BIOMES.suo&&!!DAY_FOE_BIOMES.kangas&&/1\.2/.test(moveMob.toString())&&/55\+Math\.random\(\)\*30/.test(spawnSpot.toString()));
  t('biomit: uudet alueet olemassa ja nimetty',()=>['suo','kangas','koivu','tunturi','rakka','meadow','forest','aarni','moor','mountain','peak','beach'].every(k=>BIOMES[k]&&BIOMES[k].n)&&(()=>{const f={};for(let x=-HALF;x<HALF;x+=6)for(let z=-HALF;z<HALF;z+=6)f[zoneAt(x,z)]=1;return ['suo','kangas','koivu','tunturi'].every(k=>f[k]);})());
  t('biomi: alue-ilmoitus, HUD-nimi, repun laatikko ja mänty',()=>!!$('#zoneBan')&&!!$('#biomeBox')&&typeof updateZone==='function'&&typeof renderBiome==='function'&&!!NODE.manty&&nodes.some(n=>n.type==='manty'));
  t('eläinten jalat ja kaula kiinni rungossa',()=>['peura','karju','susi','routasusi'].every(k=>{const f=MOBDEF[k].fig();f.g.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(f.body);return f.legs.every(l=>l.position.y>bb.min.y+.05);}));
  t('kuollessa kaikki valikot sulkeutuvat, Enter herättää',()=>typeof closeAllForDeath==='function'&&/Enter/.test($('#bRespawn').textContent)&&getComputedStyle($('#deadS')).cursor!=='none');
  t('rakennusnäppäimet vain rakennustilassa (isBuilding)',()=>typeof isBuilding==='function'&&(()=>{const b=buildSel;buildSel=null;const r=!isBuilding();buildSel=b;return r;})());
  t('DEV: kartan paljastus (pilvet + kohteet)',()=>!DEV||typeof devRevealMap==='function');
  t('DEV-valikko (Ä) ja V-nopeus',()=>!DEV||(!!$('#devP')&&typeof renderDev==='function'));
  return chk;});
for(const [k,v] of Object.entries(r))console.log(v===true?'OK ':'XX ',k,v===true?'':v);
console.log('errors',errs);const bad=Object.values(r).filter(v=>v!==true).length+errs.length;console.log(bad?`VIRHEITÄ: ${bad}`:'KAIKKI OK');await b.close();process.exit(bad?1:0);
