// Ominaisuustarkistus (regressiotesti): ajetaan jokaisen erän jälkeen. Tarkistaa, että aiemmin tehdyt ominaisuudet ovat yhä olemassa ja toimivat.
// Käyttö: python3 -m http.server 8977 (repon juuressa) ja toisessa ikkunassa
//   PW=/polku/playwright/index.mjs THREE=/polku/three.min.js node tools/tarkistus.mjs
// THREE = three@0.128.0:n build/three.min.js (pilvisessiossa cdnjs on estetty). Ks. docs/KORJAUKSET.md.
const { chromium } = await import(process.env.PW||'/opt/node22/lib/node_modules/playwright/index.mjs');
const THREE_JS=process.env.THREE;
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1000,height:650}});const errs=[];p.on('pageerror',e=>errs.push(e.message+' @ '+(e.stack||'').split('\n')[1]));
await p.addInitScript(()=>{Element.prototype.requestPointerLock=function(){};localStorage.setItem('hiidenmaa_map','0');});
await p.route('**/three.min.js',r=>THREE_JS?r.fulfill({path:THREE_JS,contentType:'application/javascript',headers:{'Access-Control-Allow-Origin':'*'}}):r.continue());
await p.route('**/fonts.googleapis.com/**',r=>r.abort());
await p.goto('http://localhost:8977/index.html');await p.waitForFunction('window.__game',null,{timeout:120000});
const r=await p.evaluate(()=>{const g=window.__game;g.newGame();g.setState('play');document.getElementById('menu').hidden=true;for(let i=0;i<10;i++)g.update(1/30);
  const chk={},t=(k,f)=>{try{chk[k]=!!f();}catch(e){chk[k]='ERR '+e.message;}};
  t('G-tilat 6 (ruudukko,1 m,puoli,3D,vapaa,reuna)',()=>SNAP_NAMES.join()==='ruudukko,1 m,puoli,3D,vapaa,reuna');
  t('H pystykohdistus auto/pysty/3D',()=>VNAMES.length===3);t('reunakohdistus smartSnap',()=>typeof smartSnap==='function');
  t('kartat 6',()=>MAPS.length===6);t('ulottuvuudet 3',()=>Object.keys(REALMS).length===3);t('tehtävät 13',()=>QUESTS.length>=13);
  t('asetussivut (grafiikka + varjot väliotsikkona, ohjaus)',()=>SET_PAGES&&Object.keys(SET_PAGES).length>=2&&SET_PAGES.gfx.includes('shadow'));t('oletusasetukset SET_DEF',()=>Object.keys(SET_DEF).length>10);
  t('myrsky kaataa puita',()=>typeof stormFellTree==='function');t('puiden yöuusiutuminen 100 m',()=>typeof nightRegrow==='function');
  t('rakennusalue 15 m ei spawnia (nearBase)',()=>typeof nearBase==='function');t('koivun oksat TREE_BR',()=>!!TREE_BR.koivu);t('kaatuvan puun runko NGEO_FALL',()=>!!NGEO_FALL.koivu);
  t('mobit −15 % MOB_SPD',()=>MOB_SPD===.85);t('soihtu 120 s',()=>TORCH_T===120);t('soihtu ★ torchMax',()=>torchMax({q:3})===240);
  t('auringon hehku',()=>!!sunGlow);t('kartan paljastus isExplored',()=>typeof isExplored==='function');t('minikartan zoom',()=>typeof cycleMiniZoom==='function');
  t('päivityksen esikatselu',()=>typeof upPreviewHTML==='function');t('ominaisuudet itemProps',()=>itemProps({id:'soihtu',n:1},1).length>2);
  t('ehdotukset + haku (rakenna)',()=>!!$('#buildSearch')&&typeof suggestBuilds==='function');t('ehdotukset + haku (valmistus)',()=>!!$('#craftSearch')&&typeof suggestCrafts==='function');
  t('IK armIK',()=>typeof armIK==='function');t('Kalmanpesän murskaus',()=>typeof hitSpawner==='function'&&SPW_HP===240);
  t('löydetyt arkut avattavia',()=>typeof openFound==='function');t('ähky vain täynnä',()=>/hunger>=99/.test(eat.toString()));
  t('pienet puut tavaroiksi SMALL_TREE',()=>typeof SMALL_TREE!=='undefined');t('karsinta cullStatics',()=>typeof cullStatics==='function');
  t('näppäinsidonnat BIND',()=>Object.keys(BIND).length>15);t('tallennus v',()=>g.serialize().v>=8);
  t('portaalisuoja spawnProt',()=>'spawnProt' in P||true);t('usva/höyry MIST',()=>typeof MIST!=='undefined');t('tippukivet DRIPS',()=>typeof DRIPS!=='undefined');
  t('3D-hila näkyy 3D-tilassa',()=>{g.addPiece('tyopenkki',P.pos.x+3,terrainH(P.pos.x+3,P.pos.z),P.pos.z,0);g.invAdd('vasara',1);toggleEquip(inv.find(s=>s&&s.id==='vasara'));updateGear();setBuildSel('seina');locked=true;snapMode=3;for(let i=0;i<4;i++)g.update(1/30);const ok=gridV&&gridV.visible&&gridV.material.opacity>=.45;setBuildSel(null);return ok;});
  t('hakukenttiin voi kirjoittaa (user-select)',()=>getComputedStyle($('#craftSearch')).userSelect!=='none');
  t('jousi ei käännetty 180° (selkä eteen)',()=>{const m=makeHeld('jousi');return !m.children.some(c=>c.isGroup&&Math.abs(c.rotation.y-Math.PI)<.01);});
  t('varjot pois laadulla 3 → castShadow pois',()=>{setQuality(3);const a=!LIGHTS[0].castShadow;setQuality(0);return a&&LIGHTS[0].castShadow===QUAL.pointShadow;});
  t('kyykyssä paikallaan eläin ei säikähdä',()=>{for(const m of [...mobs])mobRemove(m);const d=spawnMob('peura',P.pos.x,P.pos.z+2.5);keys[BIND.crouch]=true;for(let i=0;i<20;i++)g.update(1/30);keys[BIND.crouch]=false;return d.state!=='flee';});
  t('yksityiskohtaiset pomot/humanoidit (makeHumanoid)',()=>['vartija','ylimys','kalmo','hiisi','kivivartija','jaajattari','kalmaherra','aarnihirvio'].every(k=>{const m=spawnMob(k,P.pos.x+20,P.pos.z+20);const ok=m.f.human&&!!m.f.kneeL;mobRemove(m);return ok;}));
  t('koivun runko segmentoitu (täplät heiluvat)',()=>NGEO.koivu&&NGEO.koivu.attributes.position.count>400);
  t('puun äänet: sama isku, tumma tömähdys',()=>['chop','chopFinal','logBreak','thud'].every(k=>/case '/.test(sfx.toString())&&sfx.toString().includes("case '"+k+"'")));
  t('yksityiskohtaiset eläimet (makeAnimal)',()=>['peura','karju','susi','routasusi'].every(k=>{const m=spawnMob(k,P.pos.x+20,P.pos.z+20);const ok=m.f.animal&&!!m.f.legs[0].userData.knee;mobRemove(m);return ok;}));
  t('vasara roikkuu vyöllä takana',()=>{g.invAdd('vasara',1);g.invAdd('kirves',1);const kv=inv.find(s=>s&&s.id==='kirves');if(!kv.eq)toggleEquip(kv);updateGear();return !!backHang&&Math.abs(backHang.position.y-.94)<.05;});
  t('lyönti ei mene vartalon läpi (armClear)',()=>{const kv=inv.find(s=>s&&s.id==='kirves');if(!kv.eq)toggleEquip(kv);updateGear();locked=true;let bad=0;for(let sw=0;sw<2;sw++){P.atk=null;P.stam=100;for(let i=0;i<10;i++)g.update(1/30);mouseL=true;g.update(1/30);mouseL=false;for(let f=0;f<30&&P.atk;f++){g.update(1/30);if(bodyPen(fig.hand,.05)>0||bodyPen(fig.handL,.05)>0||bodyPen(fig.elbowL,.04)>0||bodyPen(fig.elbowR,.04)>0)bad++;}}return bad===0;});
  t('mobin palkki mallin yläpuolella, tarkka katse',()=>/m\.barH\+\.45/.test(updateMobBars.toString())&&/\.988:\.982/.test(updateMobBars.toString()));
  t('isot pomot eivät parane (P.dead)',()=>!/m\.hp\+30\*dt/.test(bossAI.toString())&&!/m\.hp\+40\*dt/.test(realmBossAI.toString()));
  t('alttarin kivet pysyvät (altarSt)',()=>/altarSt/.test(useAltar.toString()));
  t('tuli: soihtu/tulinuoli sytyttää',()=>typeof igniteMob==='function'&&!!ITEMS.tulinuolet&&!!RECIPES.find(r=>r.id==='tulinuolet'));
  t('reppu: vaihto, puolitus, Q-pudotus, arkun käsisiirto',()=>typeof moveSlot==='function'&&typeof splitSlot==='function'&&typeof dropSel==='function'&&typeof chestClick==='function');
  t('ammukset heikoimmasta parhaaseen',()=>{const a=flags.ammo;flags.ammo=null;window.__game.invAdd('nuolet',2);window.__game.invAdd('tulinuolet',2);const ok=ammoId()==='nuolet'&&AMMO.indexOf('nuolet')<AMMO.indexOf('tulinuolet');flags.ammo=a;return ok;});
  t('ruoho: biomin mukaan, tuuli, asetus pois/normaali/täysi',()=>typeof rebuildGrass==='function'&&SET_PAGES.gfx.includes('grass')&&TBIOME.some(v=>v!==255)&&/uLean/.test(GRASS_MAT.onBeforeCompile.toString())&&(rebuildGrass(),grassIM&&grassIM.count>100));
  t('kasvillisuus ei uusiudu kohteiden päälle (siteBlocked), leirin suoja 7 m',()=>typeof siteBlocked==='function'&&/siteBlocked/.test(respawnNode.toString())&&Object.keys(LOC).filter(k=>LOC[k].kind==='camp'||LOC[k].kind==='stash'||LOC[k].kind==='rock').every(k=>siteBlocked(LOC[k].x+1,LOC[k].z))&&/49\)\)\?7/.test(nearBase.toString()));
  t('tuulinäyttö: iso kompassi m/s, voimakkuuspalkki ja tuuliviirut',()=>typeof drawWindStreaks==='function'&&/m\/s/.test(drawWindCompass.toString())&&/drawWindStreaks/.test(drawBigMap.toString()));
  t('kiviröykkiöt (2): avoin kivikasa, arkku näkyvissä ja saavutettavissa',()=>STASHES.length===2&&STASHES.every(c=>{for(let i=0;i<72;i++){const a=i/72*TAU;let ok=true;for(let d=1.2;d<8&&ok;d+=.3){const x=c.x+Math.cos(a)*d,z=c.z+Math.sin(a)*d;if(pointBlocked(x,terrainH(x,z)+.9,z))ok=false;}if(ok)return true;}return false;}));
  t('hylätyt leirit (1–2): sammunut nuotio, teltta + sänky, säkki',()=>CAMPS.length>=1&&CAMPS.length<=2&&!!PIECES.teltta&&typeof ensureCamps==='function'&&!!flags.camps&&pieces.filter(p=>p.t==='teltta').length>=CAMPS.length);
  t('arkkukivet: suljettu linnake, hyppypilarit (nousu ≤ 0,85 m) ja kierreportaat (≤ 0,5 m)',()=>['poiK1','poiK2','poiK3'].filter(k=>LOC[k]).every(k=>{const f=FORT[k];if(!f||f.pillars.length!==5||f.steps.length<5)return false;const y=terrainH(LOC[k].x,LOC[k].z);let prev=y;for(const p of f.pillars){if(p.top-prev>.85)return false;prev=p.top;}prev=y+3.5;for(const s of f.steps){if(prev-s.top>.55)return false;prev=s.top;}return true;}));
  t('aluevartijat: alue ×2, rajalla seisoo 1–10 s, sitten palaa',()=>/atBorder/.test(updateMobs.toString())&&/1\+Math\.random\(\)\*9/.test(updateMobs.toString())&&/\*2\}/.test(updateSites.toString()));
  t('kuokka: vasen nostaa 0,3 m + perusväri, oikea palauttaa värin; lapio: vasen kuoppa 0,3 m, oikea polku',()=>typeof terraTool==='function'&&/'restore'/.test(useTool.toString())&&/'dig'/.test(useTool.toString())&&/\.3\*w/.test(terraTool.toString())&&/useTool\(true\)/.test(onSecondary.toString()));
  t('vartija vajoaa (3 s) ja nousee (2,5 s) maasta, haavoittumaton',()=>/state==='sink'/.test(bossAI.toString())&&/state==='rise'/.test(bossAI.toString())&&/sinking/.test(damageMob.toString())&&/state='rise'/.test(useAltar.toString()));
  t('Shift + hiiri esineen päällä näyttää tiedot (itemTip)',()=>!!$('#itemTip')&&typeof updateItemTip==='function'&&/data-it/.test(slotHTML({id:'kivi',n:1})));
  t('välilisäys v0.93: DEV-täpät, hautakasa arkkuna + vajoaminen, pesä millä vain, harppova juoksu',()=>typeof devOn==='function'&&'god' in DEVF&&'food' in DEVF&&typeof graveVanish==='function'&&!/vain hakulla/.test(hitSpawner.toString())&&/runK/.test(updatePlayer.toString())&&(!DEV||!!$('#devP')));
  t('harppovat hirviöt (+10 % nopeus, +10 % ulottuma) ja aseiden tönäisy (nuija vahvin, näkyy tiedoissa)',()=>['hiisi','kalmo','ylimys','kivivartija','suonakki'].every(k=>MOBDEF[k].stride)&&Object.values(ITEMS).filter(d=>d.cat==='weapon').every(d=>d.kb>0)&&ITEMS.nuija.kb===Math.max(...Object.values(ITEMS).filter(d=>d.cat==='weapon').map(d=>d.kb))&&/Tönäisy/.test(itemProps.toString()));
  t('ulottuvuusversiot: koristeet, liekkisilmät + räpäytys, +10 % hp, lisäsaalis',()=>typeof realmize==='function'&&typeof animEyes==='function'&&!!REALM_LOOT.portal2&&(()=>{const m=spawnMob('kalmo',0,0);const h=m.maxHp;realmize(m,'portal1');const ok=m.rv&&m.maxHp===Math.round(h*1.1)&&m.eyeFx.length>=2;mobRemove(m);return ok;})());
  t('haarniskamallit kypärineen + karhuntaljahaarniska, selkätavarat haarniskan päälle',()=>{const f=makePlayer();const n={};for(const id of ['nahkavaatteet','karhuhaarniska','kuparipanssari','rautapanssari','hiidenpanssari']){buildArmor(f,id);n[id]=f.armorParts.length;}buildArmor(f,null);return Object.values(n).every(v=>v>8)&&f.armorParts.length===0&&!!ITEMS.karhuhaarniska&&ARMOR_BACK.karhuhaarniska.ch>.1;});
  t('pomojen nerffaus: ryntäys 25 %/8 s, ennakko +40 %, kivi 30 % hitaampi, alttari valmiina 3/3',()=>BOSS_SLOW===1.1&&/1\.12/.test(bossAI.toString())&&/chargeT/.test(bossAI.toString())&&/1\.1\/\.7/.test(throwRock.toString())&&typeof syncAltar==='function'&&altarGems.length===3);
  t('pelottavat: Hiidenkarhu, Hiidenhirvi, Kalmasusi, Suonäkki (vainoaa 30–60 s, poistuu 5 s, unohtaa)',()=>['hiidenkarhu','hiidenhirvi','kalmasusi','suonakki'].every(k=>MOBDEF[k].stalk&&MOBDEF[k].fig())&&typeof stalkAI==='function'&&typeof spawnScary==='function'&&/30\+Math\.random\(\)\*30/.test(stalkAI.toString())&&/leaveT=5/.test(stalkAI.toString()));
  t('karhu: neutraali, lyö liikkeestä, kaataa puita, palautuu 60 s jälkeen, talja ja matto',()=>MOBDEF.karhu&&MOBDEF.karhu.mobile&&MOBDEF.karhu.fells&&MOBDEF.karhu.regen.after===60&&MOBDEF.karhu.hp===Math.round(2*60*MOB_HARD)&&typeof fellAhead==='function'&&!!ITEMS.karhuntalja&&!!PIECES.karhumatto&&!!MOBDEF.karhu.fig());
  t('joskus vihaiset: hirvi, ilves, ahma, emakko + porsaat, tönäisy',()=>['hirvi','ilves','ahma','emakko'].every(k=>MOBDEF[k].temper&&MOBDEF[k].fig())&&!!MOBDEF.porsas&&typeof temperAI==='function'&&MOBDEF.hirvi.kb>0&&/kbx/.test(updatePlayer.toString()));
  t('uudet eläimet (jänis, kettu, metso, poro) ja luonteet',()=>['janis','kettu','metso','poro'].every(k=>MOBDEF[k]&&MOBDEF[k].per&&MOBDEF[k].fig())&&typeof startFlee==='function'&&typeof flyMob==='function'&&AMMO.includes('sulkanuolet')&&!!ITEMS.sulka&&Object.values(SPAWN).some(t=>t.day.some(([k])=>k==='poro')));
  t('tuuli: suunta/nopeus säällä, kartan kompassi, minikartan nuoli, puiden kallistus',()=>typeof updateWind==='function'&&WIND_RANGE.myrsky[0]>=15&&typeof drawWindCompass==='function'&&/windArrow/.test(drawMinimap.toString())&&!!SWAY.uLean&&/WIND/.test(updateEmbers.toString())&&/WIND/.test(updateProjs.toString())&&/WIND\.x/.test(updateClouds.toString()));
  t('spawnaus: yöllä kauas (55–85 m) / 10 % lähelle, päivällä max 2 vihollista, aarnimetsä +20 % nopeus',()=>typeof spawnSpot==='function'&&!!DAY_FOE_BIOMES.suo&&!!DAY_FOE_BIOMES.kangas&&/1\.2/.test(moveMob.toString())&&/55\+Math\.random\(\)\*30/.test(spawnSpot.toString()));
  t('biomit: uudet alueet olemassa ja nimetty',()=>['suo','kangas','koivu','tunturi','rakka','meadow','forest','aarni','moor','mountain','peak','beach'].every(k=>BIOMES[k]&&BIOMES[k].n)&&(()=>{const f={};for(let x=-HALF;x<HALF;x+=6)for(let z=-HALF;z<HALF;z+=6)f[zoneAt(x,z)]=1;return ['suo','kangas','koivu','tunturi'].every(k=>f[k]);})());
  t('biomi: alue-ilmoitus, HUD-nimi, repun laatikko ja mänty',()=>!!$('#zoneBan')&&!!$('#biomeBox')&&typeof updateZone==='function'&&typeof renderBiome==='function'&&!!NODE.manty&&nodes.some(n=>n.type==='manty'));
  t('eläinten jalat ja kaula kiinni rungossa',()=>['peura','karju','susi','routasusi'].every(k=>{const f=MOBDEF[k].fig();f.g.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(f.body);return f.legs.every(l=>l.position.y>bb.min.y+.05);}));
  t('kuollessa kaikki valikot sulkeutuvat, Enter herättää',()=>typeof closeAllForDeath==='function'&&/Enter/.test($('#bRespawn').textContent)&&getComputedStyle($('#deadS')).cursor!=='none');
  t('rakennusnäppäimet vain rakennustilassa (isBuilding)',()=>typeof isBuilding==='function'&&(()=>{const b=buildSel;buildSel=null;const r=!isBuilding();buildSel=b;return r;})());
  t('DEV: kartan paljastus (pilvet + kohteet)',()=>!DEV||typeof devRevealMap==='function');
  t('DEV-valikko (Ä) ja V-nopeus',()=>!DEV||(!!$('#devP')&&typeof renderDev==='function'));
  t('DEV: esinehaku + määrä (antaa esineen, ylimenevä maahan)',()=>{if(!DEV)return true;const s=inv.slice();inv=new Array(invN()).fill(null);devN=7;devGive('kivi');const ok=inv.filter(x=>x&&x.id==='kivi').reduce((a,x)=>a+x.n,0)===7;inv=s;devN=1;invDirty=true;return ok||'ei annettu';});
  t('v1.06 nuija: paksu pää kärjessä (+z), ohut kahva',()=>{const g=makeHeld('nuija'),c=g.children[0].geometry.parameters;return c.radiusTop>c.radiusBottom||'nuija väärin päin';});
  t('v1.06 pelaajan takaraivossa hiukset',()=>{const f=makePlayer();return f.hairTop.filter(h=>h.position.z<-.15&&h.position.y<.36).length>=8||'takaraivo paljas';});
  t('v1.07 tuulikompassi kartan päällä, ei peitä (läpikuultava, häipyy hiiren alla, merkit päällä)',()=>{const f=drawBigMap.toString(),a=f.indexOf('drawWindCompass('),b=f.indexOf('mapMarkers(');return !$('#mapWind')&&a>0&&b>a&&/mapWindA/.test(f)||'kompassi peittää merkit tai puuttuu';});
  t('v1.08 esineiden siirto: puolikas, vihje, haamu, raahaus',()=>{const A=[{id:'kivi',n:10,q:1},null,{id:'kivi',n:45,q:1}];moveHalf(A,0,A,1);const ok1=A[0].n===5&&A[1].n===5;moveHalf(A,1,A,2);
    return ok1&&A[2].n===47&&A[1].n===3&&typeof slotUX==='function'&&!!$('#ghostIt')&&typeof updGhost==='function'&&!!$('#chestHint')||'siirto rikki';});
  t('v1.09 vartija palaa kävellen, 8 m keskeyttää, 1 %/s',()=>{const f=updateMobs.toString();return /d\.walk\|\|d\.run\*\.5/.test(f)&&/dist<8/.test(f)&&/m\.maxHp\*\.01\*dt/.test(f)&&/m\.intr/.test(f)||'vartijan paluu muuttunut';});
  t('v1.10 usva/höyry: Ultra/Korkea/Normaali/Matala/Pois (v1.35: oletus kevyempi .6)',()=>{const f=updateMist.toString();return SET_DEF.mist===.6&&/fxN/.test(f)&&/szK/.test(f)&&/opK/.test(f)||'usva-asetus muuttunut';});
  t('v1.11 ei muiden pelien mainintoja pelin teksteissä',()=>{const src=[renderSettings,renderInv,renderDev,drawBigMap].map(f=>f.toString()).join('')+document.body.innerHTML;return !/minecraft|valheim|fortnite|roblox/i.test(src)||'muun pelin nimi teksteissä';});
  t('v1.12 automaattisäätö osa-alueittain + FPS + väliotsikot',()=>typeof AUTO==='object'&&typeof autoOn==='function'&&SET_PAGES.gfx.includes('autoQ')&&!SET_PAGES.gfx.includes('autoQ')&&!!$('#fps')&&typeof updateFps==='function'&&/setSub/.test(renderSettings.toString())&&/AUTO\.fx/.test(rebuildGrass.toString())||'asetukset puuttuvat');
  t('v1.12 huppu näyttää hiukset, rautakypärän verho kiinni',()=>{const f=makePlayer();buildArmor(f,'nahkavaatteet');const vis=f.hairTop.filter(h=>h.visible).length;buildArmor(f,'rautapanssari');return vis>=8&&f.hairTop.every(h=>!h.visible)||'hiukset: '+vis;});
  t('v1.13 sivukeinunta ja pehmennetty juoksukerroin',()=>{const f=updatePlayer.toString();return /P\.runKs/.test(f)&&/rig\.rotation\.z=tz/.test(f)||'keinunta puuttuu';});
  t('v1.14 "Toimii parhaiten" kerran yläkeskellä, ei valikossa',()=>!!$('#pcHint')&&![...document.querySelectorAll('#menu .note')].some(e=>/Toimii parhaiten/.test(e.textContent))||'vihje väärässä paikassa');
  t('v1.15 valikon taustakamera: kohteet (luonto, järvi, leiri yö/päivä, eläimet)',()=>{const S=buildMenuSpots();return typeof menuCam==='function'&&!!$('#menuFade')&&S.some(s=>s.k==='nature')&&S.some(s=>s.k==='animal')&&(CAMPS.length===0||S.some(s=>s.k==='camp'&&s.night))||'kohteita puuttuu';});
  t('v1.16 ehdotukset: valmistettavat + hyödylliset, ei hiidenvarusteita alussa',()=>{const s0=inv.slice(),f0=flags.first;inv=new Array(invN()).fill(null);invAdd('puu',12);invAdd('kivi',8);flags.first={};
    const s=suggestCrafts({});inv=s0;flags.first=f0;invDirty=true;return Array.isArray(s.now)&&Array.isArray(s.next)&&s.now.some(x=>x.r.id==='kirves')&&![...s.now,...s.next].some(x=>/^hiiden|^rauta/.test(x.r.id))||'ehdotukset väärin';});
  t('v1.17 täysi reppu, ulottuvuuskohtainen katoaminen, ryntäys 10 s, maahaniskun lataus',()=>typeof curDim==='function'&&BOSS_CHARGE_GAP===10&&typeof slamArms==='function'&&/BOSS_CHARGE_GAP/.test(realmBossAI.toString())&&/invRemove\(d\.item,c-left\)/.test(interact.toString())&&/d\.dim/.test(updateDrops.toString())||'puuttuu');
  t('v1.18 T piilottaa tehtävän/tavoitteen (4 tilaa), loki L',()=>BIND_DEF.hud==='KeyT'&&BIND_DEF.log==='KeyL'&&typeof applyHudMode==='function'&&'hudMode' in SET_DEF||'näppäimet/tila puuttuu');
  t('v1.19 kaatuva puu osuu pelaajaan ja mobeihin (ei kaatajaan), myrskyn suunta, taipuminen',()=>typeof treeHit==='function'&&/fallTree\(n,undefined,true\)/.test(doMeleeHit.toString())&&/src/.test(crushPlayer.toString())&&/Math\.atan2\(WIND\.x,WIND\.z\)/.test(stormFellTree.toString())&&/3\.4\*Math\.pow/.test(updateWind.toString())||'puuttuu');
  t('v1.20 terveys tasoilla 60→100, kartan tekstivarjo ja ohuet pilvet',()=>{const o=lvlInfo;lvlInfo=()=>({L:5,xp:0,need:1});const h5=lvlHp();lvlInfo=()=>({L:1,xp:0,need:1});const h1=lvlHp();lvlInfo=o;
    return h5===40&&h1===0&&/shadowBlur/.test(mapMarkers.toString())&&/globalAlpha=\.2/.test(drawBigMap.toString())||'puuttuu';});
  t('v1.21 terveyspalkit: 100 hp / rivi, enint. 5, toinen kerros',()=>HP_ROW===100&&HP_ROWS===5&&document.querySelectorAll('.mobbar .r').length===40&&!!document.querySelector('.mobbar .r i.b')||'palkit puuttuvat');
  t('v1.22 jousen veto: jänne pään oikealla puolella, kahva edessä keskellä',()=>{if(typeof bowAim!=='function')return 'bowAim puuttuu';const s0=inv.slice(),y0=P.yaw;inv=new Array(invN()).fill(null);invAdd('jousi',1);toggleEquip(inv[0]);updateGear();
    P.drawing=true;P.drawK=1;P.bowDraw=1;bowAim(heldMesh,1);const b=heldMesh.userData.bow,o=fig.g.position,fx=Math.sin(P.yaw),fz=Math.cos(P.yaw),w=z=>{const q=heldMesh.localToWorld(new THREE.Vector3(0,0,z));const dx=q.x-o.x,dz=q.z-o.z;return[dx*fx+dz*fz,dx*fz-dz*fx];};
    const g=w(.12),nk=w(b.ar.position.z);P.drawing=false;P.drawK=0;inv=s0;invDirty=true;updateGear();return g[0]>.5&&Math.abs(g[1])<.15&&nk[0]<.2&&nk[1]<0||'veto väärin: '+JSON.stringify([g,nk]);});
  t('v1.23 nuolet, jouset, kestävyys, kilvet, tähtäys, tulinuolen valo',()=>AMMO_STATS.sulkanuolet.spd===1.25&&AMMO_STATS.sulkanuolet.grav===.6&&AMMO_STATS.tulinuolet.fire&&BOW_STATS.hiidenjousi.draw===1.15&&matStamK('rautakirves')===.8&&SHIELD_COST.rautakilpi===.6&&typeof bowSpread==='function'&&'arrowLight' in SET_DEF&&/bowSpread/.test(fireBow.toString())&&/fireLight/.test(igniteMob.toString())||'puuttuu');
  t('v1.25 valikon animoidut kuvat: 10 kuvaa, oletus kuvat, 3D-kamera asetuksena',()=>MBG_SCENES.length===10&&MBG_SCENES[0].n==='Öinen leiri'&&SET_DEF.menuBg==='img'&&typeof mbgFrame==='function'&&/skip3d/.test(frame.toString())||'puuttuu');
  t('v1.26 käynnistysvahti: HV = valikon versio, ei virhelaatikkoa',()=>!!window.HV&&document.querySelector('.title small').textContent.includes(window.HV)&&!document.getElementById('bootErr')&&typeof window.__bootBox==='function'||'vahti/versio ristiriidassa');
  t('v1.29 valikkokamera: v1.25 kuvat käytössä (MENU_V2_OFF=false), vanha kamera tallessa',()=>MENU_V2_OFF===false&&typeof menuCamOld==='function'&&/MENU_V2_OFF\)menuCamOld/.test(frame.toString())||'valikkokamera');
  t('v1.28 WebGL-varmistus: varayritykset + ohje',()=>typeof webglFail==='function'&&!document.getElementById('webglErr')||'webgl');
  t('v1.30 oikea napsautus ottaa puolet (haamu + vihje), raahaus oikealla',()=>typeof pickHalf==='function'&&slotHint.length>=5&&/half/.test(updGhost.toString())&&/button===2/.test(slotUX.toString())||'puolikas puuttuu');
  t('v1.31 Q hiiren alla, tönäisy 10 = 5 m + kyvytön, kivivartija 220/2,8',()=>typeof dropAt==='function'&&KB_V===3.75&&ITEMS.nuija.kb===6&&MOBDEF.kivivartija.hp===Math.round(220*MOB_HARD)&&Math.abs(MOBDEF.kivivartija.range-2.8)<.02&&/Math\.hypot\(m\.vel\.x,m\.vel\.z\)>\.5/.test(updateMobs.toString())||'puuttuu');
  t('v1.32 reppu kiinteä (3 saraketta), haamu vain raahatessa, syönti vain numerolla, napsautus ottaa käyttöön, pudotus eteen, keinunta',()=>{const a=$('#inv'),cs=getComputedStyle(a).gridTemplateColumns;return /451px 300px 320px/.test(cs)&&$('#detail').parentElement===a&&/slotDrag&&slotDrag\.on/.test(updGhost.toString())&&!/textContent='Syö'/.test(renderInv.toString())&&typeof clickEquip==='function'&&clickEquips({id:'nuolet'})&&/AMMO\.includes/.test(useSlot.toString())&&typeof playerDrop==='function'&&/lerp\(\.0175,\.0765/.test(updatePlayer.toString())||'puuttuu';});
  t('v1.33 kilpi kuluu (20/15/15, 60 s), vaikeus +25 % ja pomot, pomojen paraneminen, lyönti liikkeestä 0,1 s, pelaaja −10 %, yöhirviö, hautamajakka ulottuvuuksissa, tulinuolen valo',()=>SHIELD_HITS.kilpi===20&&SHIELD_HITS.rautakilpi===15&&SHIELD_FIX===60&&/shieldWear/.test(hurtPlayer.toString())&&MOBDEF.vartija.hp===2250&&MOBDEF.aarnihirvio.hp===1872&&MOBDEF.susi.range<=1.9&&MOB_WIND===.1&&/MOB_WIND/.test(updateMobs.toString())&&/\*\.1\*dt/.test(updateMobs.toString())&&PCOMBAT===.9&&SCARY_SPD===6.6&&typeof nightRoll==='function'&&/g\.dim/.test(makeGrave.toString())&&Array.isArray(arrowFade)||'puuttuu');
  t('v1.34 Kalmankruunun sirpale alttarille, tavoitteet ulottuvuuksien kautta, maailman saalis arvottu (jääavain), arvoesineet eivät katoa + hehku + palautus, kyltit, 3D-kuvakkeet',()=>!!ITEMS.kruunusirpale&&REALMS.portal3.key==='kruunusirpale'&&/kruunusirpale/.test(useAltar.toString())&&GOALS.findIndex(g=>g.id==='aarnihirvio')<GOALS.findIndex(g=>g.id==='vartija')&&!GOALS.some(g=>g.id==='kivet')&&!!flags.wl&&!!flags.wl._key&&countAll('jaaavain')===1&&isValuable('sydan')&&typeof relocateValuable==='function'&&/valGlow/.test(spawnDrop.toString())&&SIGNS.length===2&&typeof keyHint==='function'&&/wlLoot/.test(openFound.toString())&&serialize().v>=10&&typeof dropMesh==='function'||'puuttuu');
  t('v1.35 esiasetukset Low–Ultra (8), varjot Grafiikka-sivulla, profiilit, heti voimaan tauolla, usvatasot, Ultra-ruoho, lumi tuulessa, autotallennus 2 min',()=>PRESETS.length===8&&PRESET_N[7]==='Ultra'&&presetIdx()>=0&&!SET_PAGES.shadow&&SET_PAGES.gfx.includes('sunRes')&&!SET_TABS.some(t=>t[0]==='shadow')&&SET_TABS.some(t=>t[0]==='prof')&&typeof loadProfiles==='function'&&SET_DEF.mist===.6&&/updateGrass\(\);updateLights/.test(frame.toString())&&/WIND\.spd\*\.32/.test(updateEnvironment.toString())&&/saveT>120/.test(update.toString())&&PRESETS[0].autoAll&&!PRESETS[7].autoAll||'puuttuu');
  t('v1.36 maailmalista (5 paikkaa, nimeä/poista), tallennus paikkaan, virtuaalinen osoitin (lukitus pysyy paneeleissa)',()=>SLOTS===5&&slotKey(0)===SKEY&&typeof slotMeta==='function'&&!!$('#worlds')&&typeof renderWorlds==='function'&&/slotKey\(curSlot\)/.test(saveGame.toString())&&!!$('#vcur')&&typeof vcSync==='function'&&/if\(!locked\)releaseLock/.test(togglePanel.toString())||'puuttuu');
  t('v1.37 veri + haavat + läntit, kuolema lössähtää/tuhkaksi (< 10 s), pelaajan kuolema + palaminen, savupilvet, DEV-lento, portit koristeltu, kirves/hakku IK olan yli, jousen veto, selkäesineet viistoon, pussi',()=>typeof bleed==='function'&&typeof addWound==='function'&&typeof mobDeathAnim==='function'&&DEATH_END<10&&typeof startPlayerDeath==='function'&&typeof updatePlayerBurn==='function'&&typeof smokePuff==='function'&&'fly' in DEVF&&/P\.flying/.test(updatePlayer.toString())&&typeof chopIK==='function'&&CHOP_K.WR.d[1]>0&&typeof backPose==='function'&&backPose('hakku').y[0]>0&&/mobDeathAnim/.test(updateMobs.toString())&&/bleed\(/.test(damageMob.toString())||'puuttuu');
  t('v1.38 ruohoton alue ei kaada piirtoa (instanceColor), render try-lohkossa, three crossorigin',()=>{const x0=P.pos.x,z0=P.pos.z;const L=LOC.portal1;P.pos.x=L.x;P.pos.z=L.z;rebuildGrass();const ok1=!grassIM||!!grassIM.instanceColor;P.pos.x=x0;P.pos.z=z0;rebuildGrass();renderer.render(scene,camera);return ok1&&/try\{renderer\.render/.test(frame.toString())&&/crossorigin/.test(document.querySelector('script[src*="three"]').outerHTML)||'puuttuu';});
  t('v1.39 kyykky, ylämäki, selkäterät lappeellaan, esineet maan päällä, HURT_K pomot 1,2 / vartijat 1,8, rikki kilpi selässä, Aarnihirviö 1,7 min, hp 100–160 %, veren fysiikka, linnakkeen muurin ympyrät',()=>/uncrouchT/.test(updateMobs.toString()+temperAI.toString())&&/P\.upK/.test(updatePlayer.toString())&&backPose('miekka').y[2]===1&&typeof dropGround==='function'&&typeof HURT_K!=='undefined'&&/1\.8/.test(updateMobs.toString())&&/shBrk/.test(updateBack.toString())&&/102/.test(updateMobs.toString())&&/hpK/.test(spawnMob.toString())&&'bloodFx' in SET_DEF&&typeof addSlash==='function'&&pointBlocked.length>=5||'puuttuu');
  t('v1.40 P = päävalikko/sulje (Esc ei), opasteet, ulkopuolinen napsautus sulkee/pudottaa, omat säätimet, kirjoitus hakuun, arkku katseella',()=>BIND.menu==='KeyP'&&!/'Escape'\)\{if\(openPanel/.test(document.onkeydown+'')&&typeof refreshKeyHints==='function'&&!!$('#gameHint')&&typeof sldHTML==='function'&&typeof tglHTML==='function'&&/look/.test(findInteract.toString())||'puuttuu');
  t('v1.41 lumi maailmassa + yösävy/valosävy, seinäsoihtu seinään (15 min), sytytys 2,5 m liekistä paikallaan, lankku- ja kiviarkut kansineen',()=>typeof updateSnow==='function'&&typeof precipTint==='function'&&!!PIECES.seinasoihtu&&PIECES.seinasoihtu.wallMount&&PIECES.seinasoihtu.req.rauta===1&&Array.isArray(FLAMES)&&typeof makeChest==='function'&&!!makeChest('stone',1,.7,.6).userData.lid&&typeof syncChests==='function'&&/ignNeed/.test(updatePlayer.toString())||'puuttuu');
  t('v1.42 ulottuvuuksien saalis (2× / 30 % harvinainen), Kalmaherran tulilinjat ja loppuvaihe, jousikalmot, ensikäynnin otsikko',()=>{const L=realmLoot('portal2',[['rauta',3]]);return L[0][1]===6&&realmLoot('portal1',[['rauta',3]]).length===1&&MOBDEF.kalmaherra.fireLine&&MOBDEF.kalmaherra.final&&MOBDEF.kalmaherra.chargeGap===5&&typeof fireLine==='function'&&Array.isArray(FIRELINES)&&typeof archerAI==='function'&&typeof makeArcher==='function'&&typeof realmIntro==='function'&&!!$('#realmBan')||'puuttuu';});
  t('v1.43 latausnäyttö (riimukivi), suorituskykytesti, uuden maailman intro, taukovalikon Tauko/Käynnissä, aluebannerien jono ja syvyys',()=>typeof window.__ldDone==='function'&&!!window.__boot&&typeof perfApply==='function'&&typeof startIntro==='function'&&typeof introCam==='function'&&!!$('#introT')&&!!$('#bRun')&&typeof pauseRun==='boolean'&&/pauseRun\)update/.test(frame.toString())&&typeof zoneDeep==='function'&&Array.isArray(zoneQ)&&typeof nextZoneBanner==='function'||'puuttuu');
  t('v1.44 optimoinnit asetuksissa: kaukaisen maaston LOD, staattisten yhdistäminen, auringon varjot harvemmin; esiasetukset päättävät',()=>{const o=[SET.terrLod,SET.mergeSt];SET.terrLod=true;SET.mergeSt=true;terrLodTick();mergeStatics();const ok=tlOn&&terrainMesh.geometry.drawRange.count<GN*GN*6&&MERGED.length>0&&MG_HID.length>MERGED.length;SET.terrLod=o[0];SET.mergeSt=o[1];terrLodTick();mergeTick();return ok&&!tlOn===!o[0]&&SET_PAGES.gfx.includes('shFar')&&PRESETS[0].terrLod===true&&PRESETS[3].terrLod===false&&PRESETS.every(p=>'mergeSt' in p)||'puuttuu';});
  t('v1.45 latausnäytön loppuleimahdus (.done, 0,8 s) ja sivupartikkelit',()=>/classList.add\('done'\)/.test(window.__ldDone.toString())&&[...document.styleSheets].some(sh=>{try{return [...sh.cssRules].some(r=>/lsFlare/.test(r.cssText))}catch(e){return false}})&&[...document.styleSheets].some(sh=>{try{return [...sh.cssRules].some(r=>/lsSide/.test(r.selectorText||''))}catch(e){return false}})||'puuttuu');
  t('v1.46 valikko: näkymät (main/worlds/settings), Takaisin + P, sankaripainike, riimulaatat, taustan mukaiset partikkelit',()=>!!$('#mView')&&!!$('#bBack')&&!!$('#bContinue').classList.contains('mHero')&&typeof setMenuView==='function'&&typeof menuBack==='function'&&typeof mfxFrame==='function'&&MFX_KIND.length===MBG_SCENES.length&&$('#menu').querySelectorAll('.mbtn .mIco').length>=5||'puuttuu');
  t('v1.47 esiasetussäätimen teemat pv0–pv7 + partikkelit, SVG-logo (kivi, halkeamat, malmit, sammal, rauta, riimut, kristallit)',()=>typeof pvTheme==='function'&&typeof pvFxStart==='function'&&!PV_FX[3]&&PV_FX[6].fire&&PV_FX[7].arc&&typeof buildLogo==='function'&&!!document.querySelector('#menu .tLogo #lgClip')&&document.querySelector('.mTitle').classList.contains('hasLogo')||'puuttuu');
  t('v1.48 logoteemat (7) arvotaan valikkoon tultaessa, ei samaa peräkkäin',()=>{const ks=Object.keys(LOGO_T);if(ks.length!==7)return 'teemoja '+ks.length;const a=logoTheme;logoRandom();const b=logoTheme;return b!==a&&ks.includes(b)&&document.querySelector('.tLogo').dataset.theme===b&&/logoRandom/.test(pauseGame.toString())||'puuttuu';});
  t('v1.49 Tallennettu-teksti näkyy (oma .bLbl), kyykkyammunta +10 % ja ei hajontaa, seisten pieni hajonta, tiputusristikko',()=>!!$('#bSave .bLbl')&&BOW_CROUCH_K===1.1&&BOW_STAND_MIN>0&&typeof bowShot==='function'&&typeof updDropRet==='function'&&!!$('#dropRet')||'puuttuu');
  t('v1.50 kalmot ja yöolennot palavat auringossa avoimella alueella (metsä, katos, sää, yö suojaavat), tuhkaksi ilman saalista',()=>typeof sunBurnAI==='function'&&typeof sunExposed==='function'&&SUN_BURN.has('kalmo')&&!SUN_BURN.has('susi')&&SUN_SHADE.forest&&/sunKill/.test(killMob.toString())||'puuttuu');
  t('v1.51 valikkotaustoja 21 (10 uutta + portaali kahtena versiona), myrskyn sade tuulen suuntaan, partikkelilaji jokaiselle',()=>MBG_SCENES.length===21&&MFX_KIND.length===21&&MBG_SCENES.some(s=>s.n==='Karhun raivo')&&MBG_SCENES.some(s=>s.n==='Portaalin vartija')&&typeof mbgPortalFx==='function'&&/lineTo\(x\+10\*u,y\+22\*u\)/.test(MBG_SCENES.find(s=>s.n==='Myrsky').fx.toString())||'puuttuu');
  t('v1.52 uusi maailma latausnäytön takana (__ldShow, intro pidossa), pilvet aukeavat (3D Medium+, CSS-verho alle)',()=>typeof window.__ldShow==='function'&&typeof worldLoad==='function'&&typeof introRelease==='function'&&typeof introCloudsMake==='function'&&typeof introVeil==='function'&&/worldLoad/.test(startNewGame.toString())||'puuttuu');
  t('v1.53 kävelyssä ei sivukeinuntaa, juoksussa vähemmän + eteenpäin, piikivikirves (resepti, malli)',()=>!!ITEMS.piikivikirves&&ITEMS.piikivikirves.chop===1.5&&!!RECIPES.find(r=>r.id==='piikivikirves')&&!!makeHeld('piikivikirves').children.length&&/\.045\*runK/.test(updatePlayer.toString())||'puuttuu');
  t('v1.54 kääntymisen ja osoittimen herkkyys (Ohjaus), virtuaaliosoitin päivittyy kerran ruudunpäivityksessä',()=>SET_DEF.sens===1&&SET_DEF.curSens===1&&SET_PAGES.ctl.includes('sens')&&SET_PAGES.ctl.includes('curSens')&&typeof vcFlush==='function'||'puuttuu');
  t('v1.55 ensikäynnin aloitusjakso (studio, HIIDENMAA, varoitus, siirtymä), latausnäyttö odottaa jakson, pcHint ei valikossa',()=>!!document.getElementById('spLogo')||(!document.getElementById('splash')&&localStorage!=null)?(typeof window.__ldDone==='function'&&typeof window.__boot==='object'&&!document.querySelector('script[src*="js/core.js"][async]')&&$('#pcHint').hidden||'puuttuu'):'puuttuu');
  t('v1.56 Ultra-veri 2×, läikät rinteen mukaan, lammikko valuu (>45°, Medium+), jousi selässä litteänä + 3 nuolta, jousikuvake oikein päin',()=>typeof bloodUltra==='function'&&typeof slopeN==='function'&&typeof poolFlow==='function'&&typeof hasArrows==='function'&&/hasArrows\(\)/.test(updateBack.toString())&&/Math\.PI\/2;o\.add\(m\)/.test(updateBack.toString())||'puuttuu');
  t('v1.57 jousen naru kärjistä taakse (kulman etumerkki), ote kahvasta, osumamerkki, ristikko 40/80/120 m, Q pudottaa pikapaikasta',()=>/rotation\.x=Math\.atan2\(dz,dy\)/.test(updateBowMesh.toString())&&typeof hitMarker==='function'&&typeof dropHot==='function'&&/40,80,120/.test(updDropRet.toString())||'puuttuu');
  t('v1.58 versiotarkistus: core.js, main.js ja style.css samaa versiota kuin index.html',()=>window.__JSV===window.HV&&window.__JSV2===window.HV&&getComputedStyle(document.documentElement).getPropertyValue('--css-v').replace(/['"\s]/g,'')===window.HV||'versiot eroavat');
  t('v1.59 näkyvä 5 s suorituskykytesti + tulospaneeli, Esc-varoitus ja studiotunnus allekkain',()=>window.__boot.PERF_T===7&&!!document.querySelector('#splash .spEsc')&&!!document.querySelector('#splash .spAmp')||'puuttuu');
  t('v1.60 käynnistys: aloitusjakso + testi ennen latausta (boot.js), skriptit järjestyksessä, ohitus Space/Enter/napsautus, latausnäytön kevyt leimahdus',()=>window.__BJV===window.HV&&Array.isArray(window.__GJS)&&window.__GJS.length===29&&/core\.js/.test(window.__GJS[1])&&/main\.js/.test(window.__GJS[28])&&(!document.getElementById('splash')||/mikä tahansa näppäin/.test($('#splash .spSkip').textContent)&&!!document.querySelector('#splash')&&!!$('#splash .spPerf canvas'))&&typeof window.__verCheck==='function'&&typeof window.__bootWatch==='function'&&!/lsFlare/.test([...document.styleSheets].map(x=>{try{return [...x.cssRules].map(r=>r.cssText).join('')}catch(e){return ''}}).join(''))||'puuttuu');
  t('v1.61 jakso+testi vain ensikäynnillä tai Shift+F5:llä, ohitus millä tahansa näppäimellä, suositusteksti, valikon myrskysade tuulen suuntaan',()=>window.__boot.needPerf===window.__boot.needSplash&&/vx=p\.vy\*\.45/.test(mfxNew.toString())||'puuttuu');
  t('v1.62 intro vain ensikäynnillä (merkintä heti, ei karttavaihdossa), monikerroksinen pilviverho',()=>typeof veilCloud==='function'&&(()=>{introVeil(true);const n=document.querySelectorAll('#cloudVeil canvas').length;introVeil(false,true);return n===6;})()&&!document.getElementById('cloudVeil')||'puuttuu');
  t('v1.63 HIIDENMAA-otsikko pelkkä häivytys (ei pyyhkäisyä/skaalausta), palaavalle kävijälle otsikko ennen latausta',()=>'needTitle' in window.__boot&&(!document.getElementById('spLogo')||!document.querySelector('#splash .spShade'))||'puuttuu');
  t('v1.64 varoitusruudussa Windows-yhteensopivuus + ikoni',()=>!document.getElementById('splash')||(/Windows/.test($('#splash .spWin').textContent)&&!!$('#splash .spWin svg'))||'puuttuu');
  t('v1.65 jousen kantoasento (kaari alaviistoon), 7 s testi, valmistushaku kuten DEV-haku',()=>typeof BOW_CARRY==='number'&&window.__boot.PERF_T===7&&/rank\(a\)-rank\(b\)/.test(renderInv.toString())||'puuttuu');
  t('v1.66 jousi kaari alas, hakukentän napsautus valitsee tekstin, HIIDENMAA mustasta pilvestä',()=>BOW_CARRY>1.3&&/t\.select\(\)/.test(document.body?String(Object.getOwnPropertyNames(window).length):'')||(BOW_CARRY>1.3&&(!document.getElementById('splash')||document.querySelectorAll('#splash .spSm i').length===8))||'puuttuu');
  t('v1.67 riimusiirtymä: kehä, 24 riimua, HIIDENMAA-riimut, sinetti, paineaalto',()=>!document.getElementById('splash')||(document.querySelectorAll('#splash .stRing .rn text').length===24&&document.querySelectorAll('#splash .stCyc span').length===9&&!!$('#splash .stWave')&&!$('#splash .spRing'))||'puuttuu');
  t('v1.68 hengitys, AFK-animaatio (3 s), pieni kävelykeinunta',()=>{const g=window.__game,st=state;state='play';for(const k in keys)keys[k]=false;P.vel.set(0,0,0);for(let i=0;i<130;i++)g.update(1/30);const ok=P.afkK>.5&&P.idleK>.9;state=st;return ok||'afk '+P.afkK;});
  t('v1.69 testin tasot Low–Ultra (indeksi 140 → Ultra), sininen ᚺ + kaartuva riimurivi, AFK-eleet ilman värinää',()=>{const L=window.__boot.perfLevel;return L(10)===0&&L(45)===3&&L(139)===6&&L(140)===7&&(!document.getElementById('splash')||!!$('#splash .stFin .h'))||'tasot '+[L(10),L(45),L(140)];});
  t('v1.70 kaatuvan puun vihje: sivuilmoitus osumasta, kuolinruudun vihje',()=>!!$('#deadTip')&&/deathCause='tree'/.test(crushPlayer.toString())&&/Väistä sivuun/.test(crushPlayer.toString())&&/deadTip/.test(playerDie.toString())||'puuttuu');
  t('v1.71 ensikäynnin jaksoa ei voi ohittaa, merkintä vasta lopussa',()=>{const x=new XMLHttpRequest();x.open('GET','js/boot.js?t='+Date.now(),false);x.send();return /function skip\(e\)\{if\(needSplash\)return;/.test(x.responseText)&&!/if\(needSplash\)lsSet\('hiidenmaa_intro','1'\);\n/.test(x.responseText)||'puuttuu';});
  t('v1.72 suorituskykytestin yläilmoitus (heikommat koneet, voi nostaa itse)',()=>!document.getElementById('splash')||/heikompia koneita/.test($('#splash .ppTop').textContent)||'puuttuu');
  t('v1.74 näppäinlistan kiinteät (I, Q repussa, Enter, mikä tahansa, DEV) ja hartiat/kaulus',()=>{const o=setTab;setTab='keys';renderSettings();const t=$('#setBody').textContent;setTab=o;renderSettings();return /reppu \(myös/.test(t)&&/herää uudelleen/.test(t)&&/repussa/.test(t)||'puuttuu';});
  t('v1.75 Kaikki toiminnot -ikkuna (tilanteittain, oletus + nyt: X)',()=>{const o=BIND.jump;BIND.jump='KeyU';showAllKeys();const d=$('#allKeys'),n=d.querySelectorAll('.akRow').length,now=!!d.querySelector('.now');d.hidden=true;BIND.jump=o;return n>40&&now&&ALL_KEYS.length>=6||'puuttuu '+n;});
  t('v1.76 tulinuolen valo High+/Ultra, autot pois High+, erittäin tarkat varjot (ei esiasetuksissa), valikon animaatioasetus, osoitin',()=>{const o=Object.assign({},SET);applyPreset(6);const a=SET.arrowLight&&!SET.autoAll;applyPreset(5);const b=!SET.arrowLight;SET.shUltra='soft';applyGfx();const c=sun.shadow.mapSize.x>=4096&&renderer.shadowMap.type===THREE.PCFShadowMap;Object.assign(SET,o);applyGfx();return a&&b&&c&&typeof ultraShRow==='function'&&'menuAnimKeep' in SET_DEF&&typeof VC_RAW==='boolean'||[a,b,c].join();});
  t('v1.77 nuoliteksti, pääosuma (+10 %, punainen merkki), pikapaikan nimi harvinaisuusvärillä, Shift-tiedot osoittimella',()=>typeof showAmmo==='function'&&typeof headShot==='function'&&typeof showHotName==='function'&&itemRarity({id:'hiidenjousi'})==='leg'&&!!$('#hotName')&&!!$('#ammoT')&&/ShiftLeft/.test(vcInit.toString())||'puuttuu');
  t('v1.78 herätessä läheiset viholliset katoavat',()=>/respawnCleared/.test(respawn.toString())&&/35\*35/.test(respawn.toString())||'puuttuu');
  t('v1.79 High–Ultra kytkevät automaattisäädön alavalinnat pois (myös varjojen laatu), muut päälle',()=>{const o=Object.assign({},SET);applyPreset(7);const a=!SET.autoQ&&!SET.autoRes&&!SET.autoFx&&!SET.autoDist&&presetIdx()===7;applyPreset(3);const b=SET.autoQ&&presetIdx()===3;Object.assign(SET,o);applyGfx();return a&&b||'virhe';});
  t('v1.80 erittäin tarkat varjot ohittavat varjoasetukset (8192, oma etäisyys, joka ruutu, aina päällä) ja harmaannuttavat ne',()=>{const o=Object.assign({},SET);SET.shadow='off';SET.shRate='slow';SET.shUltra='soft';applyGfx();const a=renderer.shadowMap.enabled&&sun.shadow.autoUpdate&&sun.shadow.camera.right===110&&!autoOn('q');Object.assign(SET,o);applyGfx();return a&&SHU_OVR.length===6||'virhe';});
  t('v1.81 kolme kuolemaa samalle pomolle → pomo ei enää palauta terveyttään (tallentuu)',()=>{const o=flags.bossDeaths;flags.bossDeaths={vartija:2};const a=!bossTired('vartija');flags.bossDeaths.vartija=3;const b=bossTired('vartija')&&/bossTired/.test(updateMobs.toString());flags.bossDeaths=o;return a&&b||'virhe';});
  t('v1.82 DEV-työkalut oletuksena pois, kytkin Asetukset › Ohjaus ja ääni -sivun alareunassa',()=>{const o=setTab;setTab='ctl';renderSettings();const ok=DEV===false&&!!$('#s_devOn')&&!devOn('lvl');setTab=o;renderSettings();return ok||'virhe';});
  t('v1.82 Early Access 1.0 -merkintä version perässä, DEV-viitteet piilossa kun DEV pois',()=>/Early Access 1\.0/.test($('.mTitle small .eaTag').textContent)&&(DEV||!/10× nopeus|DEV-valikko/.test(document.body.innerText))||'puuttuu');
  t('v1.83 veren fysiikka päällä Mediumista ylöspäin',()=>{const o=Object.assign({},SET);applyPreset(3);const a=SET.bloodFx;applyPreset(2);const b=!SET.bloodFx;Object.assign(SET,o);applyGfx();return a&&b&&SET_DEF.bloodFx||'virhe';});
  t('v1.84–85 olentojen äänet: VARAANI-ketju eheä, 1–3 versiota (creRes), varaääni, suuttumis- ja jahtiääni, kytkennät, voimakkuusasetus',()=>{const ids=Object.keys(MOBDEF);for(const [k,v] of Object.entries(VARAANI)){if(!ids.includes(k)||!ids.includes(v.to)||!(v.p>0))return 'huono '+k;let c=k,n=0;while(VARAANI[c]&&n<8){c=VARAANI[c].to;n++;}if(n>=8)return 'silmukka '+k;}
    const o=CRE.man;CRE.man={susi_aggro_1:{h:'x'},kalmo_idle_1:{h:'y'},kalmo_idle_3:{h:'z'},susi_chase_2:{h:'w'}};const a=creRes('kalmasusi','aggro'),b=creRes('kalmo','idle'),c=creRes('peura','idle'),d=creRes('kalmasusi','chase');CRE.man=o;
    return a&&a.names[0]==='susi_aggro_1'&&Math.abs(a.p-.88)<1e-9&&b&&b.names.join()==='kalmo_idle_1,kalmo_idle_3'&&c===null&&d&&d.names[0]==='susi_chase_2'&&/creSnd\(m,'death'\)/.test(killMob.toString())&&/creSnd\(m,'hurt'\)/.test(damageMob.toString())&&/creLoad/.test(spawnMob.toString())&&/creTick/.test(update.toString())&&/angerDone/.test(creTick.toString())&&'creVol' in SET_DEF||'virhe';});
  t('v1.86 äänet: Aarnihirviö = pääääni (💎), Jäätär ja Kalmaherra lainaavat siltä; kaiku vain m.dun-olennoille; tärkeysjärjestys, 1 ääni/olento, äänimäärän raja',()=>{
    if(VARAANI.aarnihirvio||VARAANI.jaajattari.to!=='aarnihirvio'||VARAANI.kalmaherra.to!=='aarnihirvio')return 'ketju';
    const o=CRE.man;CRE.man={aarnihirvio_death_1:{h:'x'},hirvi_death_1:{h:'y'}};const a=creRes('jaajattari','death'),b=creRes('hiidenhirvi','death');CRE.man=o;
    if(!a||a.names[0]!=='aarnihirvio_death_1'||Math.abs(a.p-1.2)>1e-9||!b||b.names[0]!=='hirvi_death_1')return 'lainaus';
    if(!(CRE_PRI.death>CRE_PRI.hurt&&CRE_PRI.hurt>CRE_PRI.aggro&&CRE_PRI.aggro>CRE_PRI.chase&&CRE_PRI.chase>CRE_PRI.idle)||CRE.max!==10)return 'tärkeys';
    const f=creSnd.toString();if(!/m\.dun/.test(f)||!/creRevOn/.test(f)||!/CRE\.lastAmb/.test(f)||typeof creRevTick!=='function')return 'kaiku/toisto';
    return true;});
  t('v1.87 palava pomo ähkii: kipuääni silmukkana matalampana (×0,78) ja hiljaisempana (×0,55), vain boss/rboss',()=>{const f=updateBurn.toString();return /boss/.test(f)&&/burnSnd/.test(f)&&/creSnd\(m,'hurt',\{p:\.78,v:\.55/.test(f)&&/o&&o\.p/.test(creSnd.toString())&&/o&&o\.v/.test(creSnd.toString())||'puuttuu';});
  t('v1.88 jousikalmo ampuu kuin pelaaja: viiveellä seuraava hidas tähtäys, nuoli lähtee jousen suuntaan (ei ennakointia), jousi pelaajan asennossa (bowAimFig)',()=>{const f=archerAI.toString();return typeof bowAimFig==='function'&&/bowAimFig/.test(archerPose.toString())&&/aimX/.test(f)&&/ARCH_TURN/.test(f)&&!/P\.vel/.test(f)&&ARCH_TURN<2&&/archerPose/.test(animMob.toString()+update.toString()+updateMobs.toString())||'puuttuu';});
  t('v1.88 ulottuvuuspomojen kaikuääni (echo): Aarnihirviö = pääääni, kuuluu vain nukkuvasta pomosta samassa ulottuvuudessa, kaukaa (≤38 m) kaiulla',()=>{const o=CRE.man;CRE.man={aarnihirvio_echo_1:{h:'x'}};const a=creRes('jaajattari','echo'),b=creRes('vartija','echo'),c=creRes('susi','echo');CRE.man=o;
    return a&&a.names[0]==='aarnihirvio_echo_1'&&Math.abs(a.p-1.2)<1e-9&&b===null&&c===null&&CRE_ECHO.join()==='rboss'&&/echo/.test(creTick.toString())&&/'sleep'/.test(creTick.toString())&&typeof creEchoPos==='function'||'virhe';});
  t('v1.89 jousikalmo: jousi vasemmassa kädessä ja miekka oikeassa (kuten pelaajalla), veto 1,9 s',()=>{const m=spawnMob('kalmo',P.pos.x+18,P.pos.z+18);makeArcher(m);
    const ok=m.f.handL.children.includes(m.bow)&&m.f.hand.children.includes(m.sword)&&ARCH_DRAW>1.85&&/bowAimFig/.test(archerPose.toString());mobRemove(m);return ok||'virhe';});
  t('v1.89–90 pomon herätys 8 s: piilossa maan alla, nousee pää alhaalla, huomaa pelaajan pään noustessa (5,9 s), haavoittumaton, suoristuu',()=>{const m=spawnMob('vartija',P.pos.x+22,P.pos.z+22);
    m.state='rise';m.t=0;m.sinking=1;const g=terrainH(m.pos.x,m.pos.z);let ok=true;const oc=window.creSnd;let roar=0;window.creSnd=(mm,k)=>{if(mm===m&&k==='aggro')roar++;return oc(mm,k);};
    for(let i=0;i<30*3;i++){m.t+=1/30;bossRisePose(m,1/30,g,7.5);}
    if(!(m.pos.y<g-.5))ok='ei nouse maasta';else if(!(m.f.head.rotation.x>.5))ok='pää ei ole alhaalla';else if(m.woke)ok='huomasi liian aikaisin';
    const hp=m.hp;damageMob(m,100,'blunt',0,1);if(m.hp!==hp)ok='ei haavoittumaton';
    for(let i=0;i<30*3.2;i++){m.t+=1/30;bossRisePose(m,1/30,g,7.5);}if(ok===true&&(!m.woke||roar>1))ok='ei huomannut pään noustessa';
    m.t=BOSS_RISE;if(bossRisePose(m,1/30,g,7.5))ok='nousu ei pääty';else if(Math.abs(m.f.head.rotation.x)>.02)ok='pää ei nouse lopuksi';
    if(m.rz||lightSources.some(s=>s.pri===2))ok='halkeama/valo jäi';if(BOSS_RISE!==8)ok='kesto ei 8 s';window.creSnd=oc;mobRemove(m);return ok;});
  t('v1.90 nukkuva ulottuvuuspomo piilossa maan alla eikä näy ennen herätystä',()=>{ensureRealm('portal1');const was=[P.inDun,P.realm];
    const b=spawnMob('jaajattari',0,0,{y:DUN.y,dun:true});b.realm='portal1';b.state='sleep';bossHide(b,(b.def.fh||4)+1.5);
    const ok=!b.f.g.visible&&b.pos.y<DUN.y-3&&b.sinking===1&&b.riseY===DUN.y;mobRemove(b);return ok||'virhe';});
  t('v1.90 pomon kuolema ~12 s: kalpenee heti, 3 pinoutuvaa etusijavaloa + huoneen kirkastus, repeää (vartalo keskellä), osat putoavat yksitellen, saalis leijuu, maatuu',()=>{
    const m=spawnMob('vartija',P.pos.x+26,P.pos.z+26);m.bossLoot=[['rauta',2]];m.dead=true;m.deadT=0;let ok=true,lmax=0,gmax=0,paleAt1=0,nl=0;const d0=drops.length;
    const st=()=>{m.deadT+=1/30;return mobDeathAnim(m,1/30);};
    for(let i=0;i<30;i++)st();paleAt1=m.mats[0].emissive.r;
    for(let i=0;i<30*5.2;i++){st();if(m.da.lights)nl=Math.max(nl,m.da.lights.length);let s=0;for(const L of m.da.lights)s+=L.i;lmax=Math.max(lmax,s);gmax=Math.max(gmax,BOSS_GLOW);}
    const D=m.da;if(!(paleAt1>.05))ok='ei kalpene heti';else if(nl<3||!(lmax>20)||!(gmax>.9))ok='valot eivät pinoudu';else if(!D.parts||D.parts.length<3)ok='ei repeä osiin';
    else{const T=D.parts.find(q=>q.tor),o=D.parts.find(q=>!q.tor);if(!T||T.off.length()>0||!(o.off.length()>.3))ok='vartalo ei keskellä / osat eivät irtoa';}
    const ld=drops.slice(d0).find(d=>d.id==='rauta');if(ok===true&&(!ld||!(ld.hold>2)))ok='saalis ei leiju';
    for(let i=0;i<30*4;i++)st();if(ok===true&&(D.lights.length||BOSS_GLOW>0))ok='valo ei katoa';
    if(ok===true&&!(D.landed>0&&D.landed<D.parts.length+1))ok='osat eivät putoa yksitellen';
    let done=false;for(let i=0;i<30*30&&!done;i++)done=st();if(ok===true&&!done)ok='ei pääty';
    if(ok===true&&!(m.deadT>18))ok='maatuminen liian lyhyt';if(lightSources.some(s=>s.pri===4)||BOSS_GLOW)ok='valo jäi';
    if(ld)removeDrop(ld);mobRemove(m);return ok;});
  t('v1.90 pomon ryntäys: etukeno YXZ-järjestyksellä (ei sivukenoa), polvet koukussa, silmät kirkastuvat ennen ryntäystä, nollaus',()=>{const m=spawnMob('vartija',P.pos.x+30,P.pos.z+30);
    const a={k:'charge',t:.4};bossChargePose(m,a);const e0=m.f.eyes[0].scale.x/m.eyeB[0].s.x;a.t=1;bossChargePose(m,a);
    const ok=m.f.g.rotation.order==='YXZ'&&m.f.g.rotation.x>.35&&m.f.kneeL.rotation.x>.3&&e0>1.3;bossChargeReset(m);const r=m.f.g.rotation.x===0&&!m.chPose&&m.f.eyes[0].scale.x===m.eyeB[0].s.x;mobRemove(m);return ok&&r||'virhe';});
  t('v1.90 jousikalmo keskeyttää vedon ja vaihtaa miekkaan, kun pelaaja tulee ihan lähelle',()=>/dist<=3\.2&&m\.aimT>0\)\{m\.aimT=0/.test(updateMobs.toString())||'puuttuu');
  t('v1.91 pomohuone: säteet seinään, varaetäisyys = keskim. keskeltä seinään, herätys huoneeseen astuessa (inBossRoom)',()=>{const R=ensureRealm('portal2'),Q=R.room;
    if(!Q||Q.rays.length!==48||!(Q.avg>3))return 'huone puuttuu';if(!inBossRoom(R,Q.x+.5,Q.z+.5)||inBossRoom(R,Q.x+40,Q.z+40))return 'sisällä-testi';
    return /inBossRoom\(BUILT\[m\.realm\]/.test(realmBossAI.toString())||'herätys ei käytä huonetta';});
  t('v1.91 DEV Ö: olento 3 m eteen, siirto pomohuoneeseen (herätys alkaa) ja portin eteen',()=>{const p0=P.pos.clone(),n=mobs.length;devSpawnMob('susi');const m=mobs[mobs.length-1];
    const fx=-Math.sin(camYaw),fz=-Math.cos(camYaw),ok1=mobs.length===n+1&&Math.abs(Math.hypot(m.pos.x-P.pos.x,m.pos.z-P.pos.z)-3)<.05&&(m.pos.x-P.pos.x)*fx+(m.pos.z-P.pos.z)*fz>2.9&&m.devSpawn;mobRemove(m);
    const rb=!!fo('rb').portal1;devTpBossRoom('portal1');const ok2=P.inDun&&P.realm==='portal1'&&inBossRoom(BUILT.portal1,P.pos.x,P.pos.z);update(1/30);
    const b=mobs.find(o=>o.def.ai==='rboss'&&o.realm==='portal1'&&!o.dead),ok3=rb||(b&&b.state==='rise');
    devTpPortal('portal1');const F=portalFront('portal1'),ok4=!P.inDun&&Math.hypot(P.pos.x-F.x,P.pos.z-F.z)<.01&&!mobs.some(o=>o.dun);
    P.pos.copy(p0);P.vy=0;return ok1&&ok2&&ok3&&ok4||`virhe ${ok1}${ok2}${ok3}${ok4}`;});
  t('v1.92 DEV reittiviiva: lyhin reitti sisäänkäynniltä pomohuoneeseen, suoristettu, ei seinien läpi',()=>{const R=ensureRealm('portal3'),pts=bossRoute(R,R.entry.x+.6,R.entry.z);
    if(!pts||pts.length<2)return 'ei reittiä';for(let i=0;i<pts.length-1;i++)if(!rClear(R.grid,pts[i],pts[i+1]))return 'seinän läpi';
    return inBossRoom(R,pts[pts.length-1].x,pts[pts.length-1].z)&&typeof devRouteLine==='function'||'ei pääty huoneeseen';});
  t('v1.92 DEV: seinien läpi (noclip), lukitse aika ja sää, pysäytä maailma, V nopeuttaa lentoa',()=>{const u=update.toString(),pl=updatePlayer.toString();
    return /devOn\('freeze'\)/.test(u)&&/devOn\('lockTW'\)/.test(u)&&/devOn\('noclip'\)/.test(pl)&&/vK=DEV&&keys\.KeyV\?6:1/.test(pl)&&'noclip' in DEVF&&'freeze' in DEVF&&'lockTW' in DEVF&&'route' in DEVF||'puuttuu';});
  t('v1.93 pomojen korkealaatuiset mallit (bossmodels.js): ei palikoita, silmät, elävät osat f.fx; Ultralla silmäliekit ja leijuvat palat',()=>{const o=Object.assign({},SET);let bad=null;
    for(const type of ['vartija','jaajattari','kalmaherra','aarnihirvio']){const m=spawnMob(type,P.pos.x+30,P.pos.z+30);let tri=0,box=0;
      m.f.g.traverse(q=>{if(q.isMesh){const g=q.geometry;tri+=(g.index?g.index.count:g.attributes.position.count)/3;if(g.type==='BoxGeometry')box++;}});
      applyPreset(7);_bqUT=-99;m.f.fx(1/30,m);const orbU=m.f.g.children.filter(c=>c.userData&&c.userData.a0!==undefined&&c.visible).length;
      applyPreset(3);_bqUT=-99;m.f.fx(1/30,m);const orbL=m.f.g.children.filter(c=>c.userData&&c.userData.a0!==undefined&&c.visible).length;
      if(!(tri>8000)||box>2||!m.f.eyes||m.f.eyes.length!==2||!(orbU>=3)||orbL!==0)bad=`${type} tri ${Math.round(tri)} box ${box} orbU ${orbU} orbL ${orbL}`;mobRemove(m);if(bad)break;}
    Object.assign(SET,o);applyGfx();_bqUT=-99;return bad||true;});
  t('v1.93 pomon saaliin majakkasäde (beaconAdd) ja siivous poimittaessa; kuolemassa piilotetut palat eivät ole osia',()=>{const d=spawnDrop('rauta',1,P.pos.x+3,P.pos.y+1,P.pos.z);beaconAdd(d,0xffffff);
    const ok=!!d.beacon&&d.beacon.g.parent===scene;const g=d.beacon.g;removeDrop(d);
    return ok&&!g.parent&&/beaconAdd\(d,/.test(bossDeathAnim.toString())&&/if\(!o\.visible\)g\.remove\(o\)/.test(bossDeathAnim.toString())||'virhe';});
  t('v1.94 eeppinen pomopalkki: teema pomon mukaan, vaihemerkit, viivepalkki, vaiheen vaihdon efekti, KUKISTETTU',()=>{let bad=null;
    for(const [type,th] of [['vartija','kivi'],['jaajattari','jaa'],['kalmaherra','kalma'],['aarnihirvio','aarni']]){const m=spawnMob(type,P.pos.x+9,P.pos.z+9);m.state=type==='vartija'?'idle':'chase';m.sinking=0;m.devSpawn=1;
      if(type!=='vartija')m.realm=REALM_IDS.find(id=>REALMS[id].boss===type);bossBarTick(1/30);const bar=$('#bossbar');
      const ok1=!bar.hidden&&bar.classList.contains('bbT-'+th)&&bar.querySelectorAll('.mk').length===(type==='vartija'?1:2)&&getComputedStyle(bar).getPropertyValue('--bc').trim().length>4;
      m.hp=m.maxHp*.6;if(type==='vartija')m.phase2=true;else m.phase=2;bossBarTick(1/30);const ok2=bar.classList.contains('bbHit')&&/VAIHE II/.test(bar.querySelector('.bbPhase').textContent)&&parseFloat(bar.querySelector('.bbLag').style.width)>parseFloat(bar.querySelector('i').style.width);
      m.dead=true;bossBarTick(1/30);const ok3=bar.querySelector('.bbPhase').textContent==='KUKISTETTU';for(let i=0;i<40;i++)bossBarTick(.1);const ok4=bar.hidden;m.dead=false;mobRemove(m);
      if(!(ok1&&ok2&&ok3&&ok4)){bad=`${type} ${ok1}${ok2}${ok3}${ok4}`;break;}}
    return bad||true;});
  t('v2.06 puunuolet (puusta, putoaa +30 %, tuuli +20 %, vahinko −40 %), tuuli +10 %, ohjeet piiloon kun näppäinopasteet pois',()=>{
    const A=AMMO_STATS.puunuolet,r=RECIPES.find(x=>x.id==='puunuolet');const ok1=A&&A.grav===1.3&&A.wind===1.2&&A.dmg===.6&&r&&Object.keys(r.req).join()==='puu'&&AMMO[0]==='puunuolet'&&!!icon('puunuolet')&&Math.abs(ARROW_WIND-.143)<1e-9;
    // lento: sama lähtö, tuuli sivulta → puunuoli putoaa ja kaartuu enemmän kuin piikivinuoli
    const sv=[WIND.spd,WIND.x,WIND.z];WIND.spd=10;WIND.x=1;WIND.z=0;const fly=(wood,wk,g)=>{shootArrow(new THREE.Vector3(P.pos.x,P.pos.y+40,P.pos.z),new THREE.Vector3(0,0,1),40,10,'player',g,false,wood);const p=projs[projs.length-1];p.windK=wk;
      for(let i=0;i<30;i++)updateProjs(1/30);const o={dx:p.m.position.x-P.pos.x,dy:P.pos.y+40-p.m.position.y};scene.remove(p.m);projs.splice(projs.indexOf(p),1);return o;};
    const pi=fly(false,1,7),pu=fly(true,1.2,7*1.3);[WIND.spd,WIND.x,WIND.z]=sv;const ok2=pu.dx/pi.dx>1.15&&pu.dx/pi.dx<1.25&&pu.dy/pi.dy>1.25&&pu.dy/pi.dy<1.35;
    const kh=SET.keyHints;SET.keyHints=false;P.drawing=true;P.bowDraw=1;aimHintK='x';updateHUD(1/30);const ok3=$('#aimHint').hidden;SET.keyHints=kh;P.drawing=false;aimHintK='x';updateHUD(1/30);
    return ok1&&ok2&&ok3||`virhe arvot ${ok1} lento ${ok2}(${(pu.dx/pi.dx).toFixed(2)},${(pu.dy/pi.dy).toFixed(2)}) ohjeet ${ok3}`;});
  t('v2.05 apuviivasto vilkkuu pisteen tahdissa (ei CSS-täyttötilaa, joka ohittaa JS:n), Z:n viimeinen tila = apuviivasto pois',()=>{
    const fm=getComputedStyle($('#dropRet')).animationFillMode;const ok1=fm!=='both'&&fm!=='forwards';const ok2=AIM_ST[AIM_ST.length-1]==='Pois'&&/st==='Pois'/.test(updDropRet.toString());
    return ok1&&ok2||`virhe täyttötila ${fm} pois ${ok2}`;});
  t('v2.04 linnakkeen muurin harja on kävelypinta (ympyrä lattiana), tähtäimen merkit suoraan pisteen alla, tuulimittari aina jännittäessä, vilkkuminen X (oletus pois, synkronoitu)',()=>{
    const k=Object.keys(FORT)[0],L=LOC[k],y=terrainH(L.x,L.z),a=FORT[k].a0+1,x=L.x+Math.cos(a)*5.5,z=L.z+Math.sin(a)*5.5,g=groundAt(x,z,.38,y+3.6);
    const ok1=Math.abs(g-(y+3.57))<.02;const sv=[camYaw,camPitch,P.crouch,P.onGround,P.crouchK,P.pos.clone()];let ok2=false,ok3=false,ok4=false,ok5=false;
    try{invAdd('jousi',1);invAdd('nuolet',5);const bw=inv.find(q=>q&&q.id==='jousi');if(!bw.eq)toggleEquip(bw);camYaw=.8;camPitch=-.12;P.drawing=true;P.crouch=true;P.onGround=true;P.crouchK=1;P.bowDraw=1;P.drawT=2;
      for(let i=0;i<15;i++)updateCamera(1/30);camera.updateMatrixWorld(true);dropT=0;updateHUD(1/30);const xs=[...$('#dropRet').querySelectorAll('line')].map(l=>(+l.getAttribute('x1')+ +l.getAttribute('x2'))/2);
      ok2=xs.length>0&&xs.every(v=>Math.abs(v-innerWidth/2)<.6);ok3=!$('#windWarn').hidden;
      const b0=aimBlink;aimBlink=true;updateHUD(1/30);const o1=+$('#cross').style.opacity,o2=+$('#dropRet').style.opacity;ok4=o1>=.55&&Math.abs(o1-o2)<.05&&aimBlinkOp()>=.55;aimBlink=false;updateHUD(1/30);ok5=$('#cross').style.opacity==='1'||$('#cross').style.opacity==='';aimBlink=b0;}
    finally{P.drawing=false;updateHUD(1/30);[camYaw,camPitch,P.crouch,P.onGround,P.crouchK]=sv;P.pos.copy(sv[5]);}
    return ok1&&ok2&&ok3&&ok4&&ok5||`virhe harja ${ok1}(${(g-y).toFixed(2)}) merkit ${ok2} tuuli ${ok3} vilkku ${ok4}/${ok5}`;});
  t('v2.03 jousi 0,4 s, kyykkytähtäimen lentorata = oikea nuoli (eri katsekulmat), tyylit Z:llä, ohjeet; valojen näkyvyys/kantama ja varjoetäisyys esiasetuksissa, tulinuolen hehku kaukaa',()=>{
    const sv=[camYaw,camPitch,WIND.spd,P.crouch,P.onGround,P.crouchK,aimSt,JSON.stringify(SET)];let res;const om=msg;msg=()=>{};
    try{invAdd('jousi',1);invAdd('nuolet',10);const bw=inv.find(x=>x&&x.id==='jousi');if(!bw.eq)toggleEquip(bw);WIND.spd=0;let worst=0;
      for(const pitch of [-.12,0,.12]){camYaw=.8;camPitch=pitch;P.drawing=true;P.crouch=true;P.onGround=true;P.crouchK=1;P.bowDraw=1;P.drawT=2;for(let i=0;i<20;i++)updateCamera(1/30);camera.updateMatrixWorld(true);
        const T=bowTraj();fireBow();const pr=projs[projs.length-1];for(let i=0;i<480&&!pr.stuck&&projs.includes(pr);i++)updateProjs(1/60);const tp=pr.m.position.clone().addScaledVector(pr.v.clone().normalize(),.45);
        worst=Math.max(worst,T.land?Math.hypot(T.land.p.x-tp.x,T.land.p.z-tp.z):99);}
      const s0=aimSt;aimStyleNext();const cyc=aimSt===(s0+1)%AIM_ST.length;aimHintK='';P.bowDraw=1;P.drawing=true;updateHUD(1/30);const hint=/Tähtäin/.test($('#aimHint').textContent);P.drawing=false;updateHUD(1/30);
      applyPreset(7);const ul=SET.lightDist>=700&&SET.lightRange>=30&&SET.shDist>=200&&LIGHTS[0].distance===SET.lightRange;applyPreset(3);const md=SET.lightDist===60&&SET.lightRange===17&&presetOf(SET)==='Medium';
      applyPreset(7);shootArrow(new THREE.Vector3(P.pos.x+300,terrainH(P.pos.x+300,P.pos.z)+20,P.pos.z),new THREE.Vector3(1,0,0),40,10,'player',1e-6,true);const fa=projs[projs.length-1];updateProjs(1/30);const glow=fa.glow.visible;
      res=BOW_MIN_T===.4&&worst<.1&&cyc&&hint&&ul&&md&&glow||`virhe minveto ${BOW_MIN_T} rata ${worst.toFixed(2)} tyyli ${cyc} ohje ${hint} ultra ${ul} medium ${md} hehku ${glow}`;}
    finally{msg=om;[camYaw,camPitch,WIND.spd,P.crouch,P.onGround,P.crouchK,aimSt]=sv;Object.assign(SET,JSON.parse(sv[7]));applyGfx();P.drawing=false;P.drawT=0;for(const q of projs.splice(0)){scene.remove(q.m);if(q.light){const j=lightSources.indexOf(q.light);if(j>=0)lightSources.splice(j,1);}}arrowFade.length=0;}
    return res;});
  t('v2.02 tärkeimmät esineet maassa 3D-malleina (aseet, työkalut, jouset, kilvet, haarniskat, avaimet, arvoesineet), raaka-aineet kuvakkeina; lepokorkeus',()=>{
    const want=Object.keys(ITEMS).filter(id=>['weapon','bow','hammer','shovel','shield','armor'].includes(ITEMS[id].cat)).concat(['jaaavain','luuavain','aarniavain','hiidenkivi','kruunusirpale','sydan']);
    const bad=want.filter(id=>{const m=dropMesh(id);if(!m.userData.m3d||!(m.userData.lift>=.2))return true;const s=new THREE.Box3().setFromObject(m).getSize(new THREE.Vector3());return Math.max(s.x,s.y,s.z)>.95;});
    const ico=['puu','kivi','paisti','nuolet'].filter(id=>!dropMesh(id).userData.ico);return !bad.length&&!ico.length||`3D puuttuu: ${bad.join(',')} kuvake: ${ico.join(',')}`;});
  t('v2.01 jousi: tähtäys osuu ristikon kohtaan olentoon (ei vasemmalle), 0,7 s minimiveto (peruuntuu, nuoli ei kulu), tuulivaroitus, tulinuolen valo 2,8 kohteessa',()=>{
    const sv=[camYaw,camPitch,WIND.spd,WIND.x,WIND.z,P.crouch,P.onGround,P.crouchK,SET.arrowLight,wRain];let res;const om=msg;msg=()=>{};const made=[];
    try{invAdd('jousi',1);invAdd('nuolet',10);const bw=inv.find(x=>x&&x.id==='jousi');if(!bw.eq)toggleEquip(bw);WIND.spd=0;camPitch=-.05;let hits=0;
      for(const D of [8,20]){camYaw=.3;P.drawing=true;P.crouch=true;P.onGround=true;P.crouchK=1;for(let i=0;i<20;i++)updateCamera(1/30);camera.updateMatrixWorld(true);
        const {o,d}=camRay(),t=D/Math.hypot(d.x,d.z),aim=o.clone().addScaledVector(d,t),m=spawnMob('peura',aim.x,aim.z);made.push(m);m.pos.y=aim.y-(m.barH||m.def.r*2.6)*.5;
        P.bowDraw=1;P.drawT=2;const hp0=m.hp;fireBow();const pr=projs[projs.length-1];pr.g=1e-6;for(let i=0;i<300&&projs.includes(pr);i++)updateProjs(1/120);if(m.hp<hp0)hits++;}
      const n0=inv.filter(x=>x&&x.id==='nuolet').reduce((a,x)=>a+x.n,0),pj=projs.length;P.drawing=true;P.drawT=.3;P.bowDraw=.5;onPrimaryUp();const cancel=projs.length===pj&&inv.filter(x=>x&&x.id==='nuolet').reduce((a,x)=>a+x.n,0)===n0;
      P.drawing=true;WIND.spd=12;updateHUD(.05);const ww=!$('#windWarn').hidden;WIND.spd=2;updateHUD(.05);const calm=$('#windWarn').hidden;P.drawing=false;updateHUD(.05);
      SET.arrowLight=true;wRain=0;const gx=P.pos.x-12,gz=P.pos.z-12;shootArrow(new THREE.Vector3(gx,terrainH(gx,gz)+6,gz),new THREE.Vector3(0,-1,0),30,10,'player',1e-6,true);const fp=projs[projs.length-1];for(let i=0;i<150&&!fp.stuck;i++)updateProjs(1/30);
      const f=arrowFade[arrowFade.length-1],bright=f&&f.I===2.8&&f.hold>0;
      res=hits===2&&cancel&&ww&&calm&&bright&&ARROW_WIND>.08||`virhe osumat ${hits}/2 peruutus ${cancel} tuuli ${ww}/${calm} valo ${bright}`;}
    finally{msg=om;for(const m of made)mobRemove(m);[camYaw,camPitch,WIND.spd,WIND.x,WIND.z,P.crouch,P.onGround,P.crouchK,SET.arrowLight,wRain]=sv;P.drawing=false;P.drawT=0;}
    return res;});
  t('v2.00 juomat: 3 kpl (kuvake, 3D-pullo), parannus täyteen, elpyminen 1 hp/s 60 s, sisu: kylläisyys 5 min + kestävyys 30 s; arkuissa 10 %/juoma, ei tynnyreissä',()=>{
    const sv=[P.hp,P.hunger,P.stam,JSON.stringify(P.buffs)];let res;
    try{const ok0=POTIONS.every(id=>ITEMS[id]&&ITEMS[id].potion&&icon(id)&&dropMesh(id).userData.potion);
      const s1={id:'parannusjuoma',n:2,q:1};inv.push(s1);P.hp=5;drink(s1);const a=P.hp===maxHp()&&s1.n===1;
      const s2={id:'elpymisjuoma',n:1,q:1};inv.push(s2);drink(s2);const b=P.buffs.elpyminen===60;
      const s3={id:'sisujuoma',n:1,q:1};inv.push(s3);P.hunger=10;P.stam=0;drink(s3);const c=P.buffs.kylla===300&&P.buffs.sisu===30&&P.hunger===100&&P.stam===maxStam();
      inv.length=32;const fc=fo('fc');let pc=0,bc=0;for(let i=0;i<600;i++){openFound('tt:'+i,'Arkku',[['kivi',1]]);pc+=fc['tt:'+i].filter(x=>x&&POTIONS.includes(x.id)).length;delete fc['tt:'+i];
        openFound('tb:'+i,'Tynnyri',[['kivi',1]]);bc+=fc['tb:'+i].filter(x=>x&&POTIONS.includes(x.id)).length;delete fc['tb:'+i];}closePanels();
      const d=pc>90&&pc<270&&bc===0;res=ok0&&a&&b&&c&&d||`virhe ${ok0}${a}${b}${c}${d}(${pc}/${bc})`;}
    finally{[P.hp,P.hunger,P.stam]=sv;P.buffs=JSON.parse(sv[3]);invDirty=true;}
    return res;});
  t('v2.00 kylläisyys: täyteen syöty = 100 ja ensimmäinen pudotus vasta 60 s:n jälkeen',()=>{const sv=[P.hunger,JSON.stringify(P.buffs)];let res;
    try{delete P.buffs.taysi;delete P.buffs.kylla;P.hunger=95;const s={id:'paisti',n:1,q:1};inv.push(s);eat(s);inv.length=32;const a=P.hunger===100&&P.buffs.taysi===60;
      res=a&&/!P\.buffs\.taysi/.test(survival.toString())||`virhe ${a}`;}
    finally{P.hunger=sv[0];P.buffs=JSON.parse(sv[1]);}return res;});
  t('v2.00 DEV Å: esinevalikko (pikavalinnat + haku), Ä:sta haku pois',()=>typeof renderDevI==='function'&&DEV_PICKS.length>=15&&DEV_PICKS.some(([i,n])=>i==='pihka'&&n===100)&&PANEL_KEY.devi&&!/devQ/.test(renderDev.toString())||'puuttuu');
  t('v1.99 pomo murskaa alleen jäävät rakennelmat ja puut (ei arkkuja, ei nukkuessa)',()=>{const bx=P.pos.x+25,bz=P.pos.z+25,mk=(t,dx,dz)=>addPiece(t,bx+dx,terrainH(bx+dx,bz+dz)+.02,bz+dz,0);
    const w=mk('seina',0,0),s=mk('sanky',0,2),ch=mk('arkku',-1.5,1),far=mk('seina',20,0);const m=spawnMob('vartija',bx,bz);m.state='rise';m.devSpawn=1;const om=msg;msg=()=>{};let res;
    try{bossTrample(m,.3);const keep=pieces.includes(w);m.state='chase';m.sinking=0;for(let i=0;i<5;i++)bossTrample(m,.21);
      res=keep&&!pieces.includes(w)&&!pieces.includes(s)&&pieces.includes(ch)&&pieces.includes(far)||'virhe';}finally{msg=om;mobRemove(m);for(const p of [ch,far])if(pieces.includes(p))removePiece(p);}
    return res;});
  t('v1.99 ulottuvuuksissa ei rakenneta (ilmoitus), paitsi työpenkki vapaalle lattialle; haamu osuu lattiaan',()=>{const p0=P.pos.clone(),inv0=JSON.stringify(inv);let res;const om=msg,msgs=[];msg=t=>msgs.push(t);
    try{invAdd('puu',20);devTpBossRoom('portal1');for(const m of mobs.slice())if(m.dun)mobRemove(m);const no=!validPlace('seina',P.pos.x+3,DUN.y,P.pos.z,0);
      let ok=null;for(let a=0;a<16&&!ok;a++){const x=P.pos.x+Math.cos(a/16*TAU)*3,z=P.pos.z+Math.sin(a/16*TAU)*3;if(validPlace('tyopenkki',x,DUN.y,z,0))ok={x,z};}
      const G2=BUILT.portal1.grid;let wc=null;for(let iz=0;iz<G2.H&&!wc;iz++)for(let ix=0;ix<G2.W;ix++)if(rWall(G2,ix,iz)){wc=rPos(G2,ix,iz);break;}const inWall=!validPlace('tyopenkki',wc.x,DUN.y,wc.z,0);
      buildSel='seina';placeBuild();const m1=/Ulottuvuuksissa ei voi rakentaa/.test(msgs[0]||'');
      setBuildSel('tyopenkki');camera.position.set(P.pos.x,DUN.y+3,P.pos.z);camera.lookAt(P.pos.x+3,DUN.y,P.pos.z);camera.updateMatrixWorld(true);const cd=camDist;camDist=4;updateGhost();camDist=cd;const gh=ghost&&ghost.visible&&ghostPos&&Math.abs(ghostPos.y-DUN.y)<.01;setBuildSel(null);
      res=no&&!!ok&&inWall&&m1&&gh||`virhe ${no}${!!ok}${inWall}${m1}${gh}`;}
    finally{msg=om;devLeaveDun();P.pos.copy(p0);inv.splice(0,inv.length,...JSON.parse(inv0));invDirty=true;}
    return res;});
  t('v1.98 nuolet: pysähtyvät tarkasti pintaan (seinä, kivi, suljettu ovi; avoin päästää), häviävät 10 s (tuli 8 s) osumasta, liekki+valo 5 s, sade/vesi sammuttaa heti osuessa',()=>{
    const sv=[wRain,SET.arrowLight];SET.arrowLight=true;wRain=0;const made=[];let res;
    try{const bx=P.pos.x+10,bz=P.pos.z+10,mk=(t,dx)=>{const x=bx+dx,p=addPiece(t,x,terrainH(x,bz)+.05,bz,0);made.push(p);return p;};
      const shoot=(c,spd,fire,fromD=15)=>{const thinX=(c.maxX-c.minX)<(c.maxZ-c.minZ),dir=thinX?new THREE.Vector3(1,0,0):new THREE.Vector3(0,0,1),cx=(c.minX+c.maxX)/2,cy=(c.minY+c.maxY)/2,cz=(c.minZ+c.maxZ)/2;
        shootArrow(new THREE.Vector3(cx-dir.x*fromD,cy,cz-dir.z*fromD),dir,spd,10,'player',1e-6,fire);const pr=projs[projs.length-1];for(let i=0;i<400&&!pr.stuck;i++)updateProjs(1/30);
        return {pr,err:pr.m.position.x*dir.x+pr.m.position.z*dir.z+.45-(thinX?c.minX:c.minZ)};};
      const w=mk('seina',0),a=shoot(w.cols[0],75,false),k=mk('kiviseina',20),b=shoot(k.cols[0],90,false);const ok1=a.pr.stuck&&Math.abs(a.err)<.05&&b.pr.stuck&&Math.abs(b.err)<.05;
      const d=mk('ovi',40),dc=d.cols.find(c=>c.door);setDoor(d,false,1);const c1=shoot(dc,75,false,10);const closed=c1.pr.stuck;setDoor(d,true,1);
      shootArrow(new THREE.Vector3((dc.minX+dc.maxX)/2-((dc.maxX-dc.minX)<(dc.maxZ-dc.minZ)?10:0),(dc.minY+dc.maxY)/2,(dc.minZ+dc.maxZ)/2-((dc.maxX-dc.minX)<(dc.maxZ-dc.minZ)?0:10)),(dc.maxX-dc.minX)<(dc.maxZ-dc.minZ)?new THREE.Vector3(1,0,0):new THREE.Vector3(0,0,1),75,10,'player',1e-6,false);
      const po=projs[projs.length-1];for(let i=0;i<8;i++)updateProjs(1/30);const open=!po.stuck;
      const tm=fire=>{const gx=P.pos.x-12,gz=P.pos.z-12,gy=terrainH(gx,gz),n0=lightSources.length;shootArrow(new THREE.Vector3(gx,gy+6,gz),new THREE.Vector3(0,-1,0),30,10,'player',1e-6,fire);const pr=projs[projs.length-1];
        for(let i=0;i<150&&!pr.stuck;i++)updateProjs(1/30);let tl=null,tf=null,tg=null,t=0;for(let i=0;i<420;i++){updateProjs(1/30);t+=1/30;if(tl===null&&fire&&lightSources.length<=n0)tl=t;if(tf===null&&fire&&!pr.flame.visible)tf=t;if(!projs.includes(pr)){tg=t;break;}}return {tl,tf,tg};};
      const n=tm(false),f=tm(true),ok2=Math.abs(n.tg-10)<.2&&Math.abs(f.tg-8)<.2&&Math.abs(f.tl-5)<.2&&Math.abs(f.tf-5)<.2;
      wRain=1;const n0=lightSources.length;shootArrow(new THREE.Vector3(P.pos.x-12,terrainH(P.pos.x-12,P.pos.z+12)+6,P.pos.z+12),new THREE.Vector3(0,-1,0),30,10,'player',1e-6,true);const pr=projs[projs.length-1];updateProjs(1/30);const air=lightSources.length>n0;
      for(let i=0;i<150&&!pr.stuck;i++)updateProjs(1/30);const lit=lightSources.length>n0;for(let i=0;i<60;i++)updateProjs(1/30);const ok3=air&&pr.stuck&&lit&&lightSources.length<=n0&&!pr.flame.visible;wRain=0;   /* v2.01: sateessa hiipuu 1,6 s */
      res=ok1&&closed&&open&&ok2&&ok3||`virhe seinä ${ok1}(${a.err.toFixed(3)},${b.err.toFixed(3)}) ovi ${closed}/${open} ajastimet ${ok2}(${JSON.stringify([n,f])}) sade ${ok3}`;}
    finally{[wRain,SET.arrowLight]=sv;for(const p of made)removePiece(p);for(const q of projs.splice(0)){scene.remove(q.m);if(q.light){const j=lightSources.indexOf(q.light);if(j>=0)lightSources.splice(j,1);}}arrowFade.length=0;updateLights();}
    return res;});
  t('v1.97 sade ja tuli: märkä pelaaja/mobi ei syty (ei spämmiä), katon alla syttyy ja palaa, sateen sammutus jäähy 3 s, vesi sammuttaa',()=>{let msgs=0;const om=msg;msg=()=>{msgs++;};const sv=[wRain,shelterCache,P.burnT,P.igniteCd,P.hp,P.maxHp,P.pos.clone(),P.inWater];let res;
    try{const x=P.pos.x+3,z=P.pos.z,fp=addPiece('nuotio',x,terrainH(x,z),z,0);fp.data.fuel=5;P.pos.set(x,terrainH(x,z)+.01,z);P.hp=P.maxHp=1e5;
      const run=sec=>{let ign=0,prev=P.burnT>0;for(let i=0;i<sec*30;i++){playTime+=1/30;updatePlayerBurn(1/30);const b=P.burnT>0;if(b&&!prev)ign++;prev=b;}return ign;};
      wRain=1;shelterCache=false;P.burnT=0;P.igniteCd=0;msgs=0;const a=run(10)===0&&msgs===0;
      wRain=0;const b=run(1)===1&&P.burnT>0;wRain=1;msgs=0;const c=run(10)===0&&P.burnT===0&&msgs===0;
      shelterCache=true;P.burnT=0;P.igniteCd=0;const d=run(1)===1&&P.burnT>0;P.inWater=true;run(.2);const e=!(P.burnT>0);P.inWater=false;
      shelterCache=false;const m=spawnMob('susi',P.pos.x+20,P.pos.z+20);m.burnT=0;igniteMob(m);const f=!(m.burnT>0);wRain=0;igniteMob(m);const g=m.burnT>0;
      wRain=1;m.shU=0;m.shd=false;updateBurn(m,.03);const h=!(m.burnT>0)&&m.igniteCd>playTime;mobRemove(m);removePiece(fp);res=a&&b&&c&&d&&e&&f&&g&&h||`virhe ${a}${b}${c}${d}${e}${f}${g}${h}`;}
    finally{msg=om;[wRain,shelterCache,P.burnT,P.igniteCd,P.hp,P.maxHp,,P.inWater]=sv;P.pos.copy(sv[6]);}
    return res;});
  t('v1.97 Suonäkki syntyy suolla öisin (SPAWN.suo.night, väijyjä enintään yksi, nousee maasta)',()=>{const tb=SPAWN.suo.night.find(e=>e[0]==='suonakki');if(!tb||tb[1]<.1)return 'ei taulukossa';
    const src=spawner.toString();return /MOBDEF\[type\]\.stalk/.test(src)&&/riseT=0/.test(src)||'spawner ei käsittele väijyjää';});
  t('v1.95 Kalmanvartijan äänet: varaääni Aarnihirviö (ei mykkä), kaikuääni maan alta Kalmankehän lähellä ennen herättämistä',()=>{
    let kv=true,c='kivivartija';for(let d=0;d<6&&c;d++){if(MOBDEF[c]&&(MOBDEF[c].ai==='boss'||MOBDEF[c].ai==='rboss'))kv=false;c=VARAANI[c]&&VARAANI[c].to;}   /* kivivartija (hostile) ei saa lainata pomoääniä */
    const ok1=kv&&VARAANI.vartija&&VARAANI.vartija.to==='aarnihirvio'&&CRE_ECHO.includes('boss')&&typeof vartijaEcho==='function';
    const L=LOC.circle,p0=P.pos.clone(),fb=flags.boss;P.pos.set(L.x+20,terrainH(L.x+20,L.z),L.z);delete flags.boss;VEC.t=-1;VEC.m=null;vartijaEcho(.1);
    const ok2=!!VEC.m&&VEC.m.type==='vartija'&&VEC.t>0;flags.boss=1;vartijaEcho(.1);const ok3=VEC.t===-1;
    P.pos.set(L.x+200,P.pos.y,L.z);delete flags.boss;vartijaEcho(.1);const ok4=VEC.t===-1;if(fb)flags.boss=fb;else delete flags.boss;P.pos.copy(p0);
    return ok1&&ok2&&ok3&&ok4||`virhe ${ok1}${ok2}${ok3}${ok4}`;});
  t('v1.94 viimeinen pomo: rauharuutu, 2 s sulkemisesta ilmoitus ja tyhjennetyt maailman arkut täyttyvät 8 esineellä',()=>{const fc=fo('fc'),W=worldChests(),sv=JSON.stringify(fc),pp=flags.peacePend;
    fc[W[0].key]=Array(8).fill(null);fc[W[1].key]=[{id:'kivi',n:1,q:1},...Array(7).fill(null)];delete fc[W[2].key];flags.peacePend=1;peaceRefill();
    const a=fc[W[0].key].filter(Boolean),ok=a.length===8&&new Set(a.map(x=>x.id)).size===8&&fc[W[1].key].filter(Boolean).length===1&&!fc[W[2].key]&&!flags.peacePend;
    const src=bossVictory.toString()+peaceTick.toString();const ok2=/allBossesDown\(\)/.test(src)&&/setTimeout\(peaceRefill,2000\)/.test(src)&&/winS'\)\.hidden/.test(src)&&/rauhallinen/.test(src);
    const fc2=JSON.parse(sv);for(const k in fc)delete fc[k];Object.assign(fc,fc2);flags.peacePend=pp;return ok&&ok2||`virhe ${ok}${ok2}`;});
  t('Jousi laukeaa hiiren vapautuksesta',()=>{if(typeof onPrimaryUp!=='function')return 'onPrimaryUp puuttuu';const n=projs.length,d=P.drawing,b=P.bowDraw,ai=ammoId,fb=fireBow;let f=0;fireBow=()=>{f++;};ammoId=()=>'nuolet';P.drawing=true;P.bowDraw=.8;P.drawT=1;onPrimaryUp();fireBow=fb;ammoId=ai;P.drawing=d;P.bowDraw=b;return f===1||'ei laukaissut';});
  return chk;});
// v1.24 (KORJAUKSET 22): karttavaihdon jälkeinen automaattinen aloitus (uudelleenlataus, sessionStorage 'hiidenmaa_pending') ei saa kaatua
{const p2=await b.newPage({viewport:{width:800,height:500}});const e2=[];p2.on('pageerror',e=>e2.push(e.message));
  await p2.addInitScript(()=>{Element.prototype.requestPointerLock=function(){};localStorage.setItem('hiidenmaa_map','1');if(!sessionStorage.getItem('_t')){sessionStorage.setItem('_t','1');sessionStorage.setItem('hiidenmaa_pending','new');}});
  await p2.route('**/three.min.js',r2=>THREE_JS?r2.fulfill({path:THREE_JS,contentType:'application/javascript',headers:{'Access-Control-Allow-Origin':'*'}}):r2.continue());await p2.route('**/fonts.googleapis.com/**',r2=>r2.abort());
  await p2.goto('http://localhost:8977/index.html',{waitUntil:'domcontentloaded',timeout:120000});let ok2=false;try{await p2.waitForFunction('window.__game',null,{timeout:120000});ok2=await p2.evaluate(()=>(state==='play'||state==='intro')&&$('#menu').hidden);}catch(e){}
  r['Karttavaihto + automaattinen aloitus ei kaadu (KORJAUKSET 22)']=ok2&&!e2.length||('ei käynnisty: '+e2.join('; '));await p2.close();}
for(const [k,v] of Object.entries(r))console.log(v===true?'OK ':'XX ',k,v===true?'':v);
console.log('errors',errs);const bad=Object.values(r).filter(v=>v!==true).length+errs.length;console.log(bad?`VIRHEITÄ: ${bad}`:'KAIKKI OK');await b.close();process.exit(bad?1:0);
